<?php
// autogenerated file 29.05.2009 15:17
// $Id: $
// $Log: $
//
//
require_once 'AddItemResponseContainerType.php';
require_once 'AbstractResponseType.php';

class AddItemsResponseType extends AbstractResponseType
{
	// start props
	// @var AddItemResponseContainerType $AddItemResponseContainer
	var $AddItemResponseContainer;
	// end props

/**
 *

 * @return AddItemResponseContainerType
 * @param  $index 
 */
	function getAddItemResponseContainer($index = null)
	{
		if ($index) {
		return $this->AddItemResponseContainer[$index];
	} else {
		return $this->AddItemResponseContainer;
	}

	}
/**
 *

 * @return void
 * @param  $value 
 * @param  $index 
 */
	function setAddItemResponseContainer($value, $index = null)
	{
		if ($index) {
	$this->AddItemResponseContainer[$index] = $value;
	} else {
	$this->AddItemResponseContainer = $value;
	}

	}
/**
 *

 * @return 
 */
	function AddItemsResponseType()
	{
		$this->AbstractResponseType('AddItemsResponseType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'AddItemResponseContainer' =>
				array(
					'required' => false,
					'type' => 'AddItemResponseContainerType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => true,
					'cardinality' => '0..*'
				)
			));

	}
}
?>
