<?php
// autogenerated file 29.05.2009 15:17
// $Id: $
// $Log: $
//
//
require_once 'AddItemRequestContainerType.php';
require_once 'AbstractRequestType.php';

class AddItemsRequestType extends AbstractRequestType
{
	// start props
	// @var AddItemRequestContainerType $AddItemRequestContainer
	var $AddItemRequestContainer;
	// end props

/**
 *

 * @return AddItemRequestContainerType
 * @param  $index 
 */
	function getAddItemRequestContainer($index = null)
	{
		if ($index) {
		return $this->AddItemRequestContainer[$index];
	} else {
		return $this->AddItemRequestContainer;
	}

	}
/**
 *

 * @return void
 * @param  $value 
 * @param  $index 
 */
	function setAddItemRequestContainer($value, $index = null)
	{
		if ($index) {
	$this->AddItemRequestContainer[$index] = $value;
	} else {
	$this->AddItemRequestContainer = $value;
	}

	}
/**
 *

 * @return 
 */
	function AddItemsRequestType()
	{
		$this->AbstractRequestType('AddItemsRequestType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'AddItemRequestContainer' =>
				array(
					'required' => false,
					'type' => 'AddItemRequestContainerType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => true,
					'cardinality' => '0..*'
				)
			));

	}
}
?>
