<?php
// autogenerated file 29.05.2009 15:17
// $Id: $
// $Log: $
//
//
require_once 'AbstractResponseType.php';

class AddMemberMessageAAQToPartnerResponseType extends AbstractResponseType
{
	// start props
	// end props

/**
 *

 * @return 
 */
	function AddMemberMessageAAQToPartnerResponseType()
	{
		$this->AbstractResponseType('AddMemberMessageAAQToPartnerResponseType', 'urn:ebay:apis:eBLBaseComponents');

	}
}
?>
