<?php
// autogenerated file 29.05.2009 15:17
// $Id: $
// $Log: $
//
//
require_once 'AbstractRequestType.php';

class AddSellingManagerInventoryFolderRequestType extends AbstractRequestType
{
	// start props
	// @var string $FolderName
	var $FolderName;
	// @var long $ParentFolderID
	var $ParentFolderID;
	// @var string $Comment
	var $Comment;
	// end props

/**
 *

 * @return string
 */
	function getFolderName()
	{
		return $this->FolderName;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setFolderName($value)
	{
		$this->FolderName = $value;
	}
/**
 *

 * @return long
 */
	function getParentFolderID()
	{
		return $this->ParentFolderID;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setParentFolderID($value)
	{
		$this->ParentFolderID = $value;
	}
/**
 *

 * @return string
 */
	function getComment()
	{
		return $this->Comment;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setComment($value)
	{
		$this->Comment = $value;
	}
/**
 *

 * @return 
 */
	function AddSellingManagerInventoryFolderRequestType()
	{
		$this->AbstractRequestType('AddSellingManagerInventoryFolderRequestType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'FolderName' =>
				array(
					'required' => false,
					'type' => 'string',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'ParentFolderID' =>
				array(
					'required' => false,
					'type' => 'long',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'Comment' =>
				array(
					'required' => false,
					'type' => 'string',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				)
			));

	}
}
?>
