<?php
// autogenerated file 29.05.2009 15:17
// $Id: $
// $Log: $
//
//
require_once 'SellingManagerProductDetailsType.php';
require_once 'FeesType.php';
require_once 'AbstractResponseType.php';

class AddSellingManagerTemplateResponseType extends AbstractResponseType
{
	// start props
	// @var long $CategoryID
	var $CategoryID;
	// @var long $Category2ID
	var $Category2ID;
	// @var long $SaleTemplateID
	var $SaleTemplateID;
	// @var long $SaleTemplateGroupID
	var $SaleTemplateGroupID;
	// @var string $SaleTemplateName
	var $SaleTemplateName;
	// @var SellingManagerProductDetailsType $SellingManagerProductDetails
	var $SellingManagerProductDetails;
	// @var FeesType $Fees
	var $Fees;
	// end props

/**
 *

 * @return long
 */
	function getCategoryID()
	{
		return $this->CategoryID;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setCategoryID($value)
	{
		$this->CategoryID = $value;
	}
/**
 *

 * @return long
 */
	function getCategory2ID()
	{
		return $this->Category2ID;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setCategory2ID($value)
	{
		$this->Category2ID = $value;
	}
/**
 *

 * @return long
 */
	function getSaleTemplateID()
	{
		return $this->SaleTemplateID;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setSaleTemplateID($value)
	{
		$this->SaleTemplateID = $value;
	}
/**
 *

 * @return long
 */
	function getSaleTemplateGroupID()
	{
		return $this->SaleTemplateGroupID;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setSaleTemplateGroupID($value)
	{
		$this->SaleTemplateGroupID = $value;
	}
/**
 *

 * @return string
 */
	function getSaleTemplateName()
	{
		return $this->SaleTemplateName;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setSaleTemplateName($value)
	{
		$this->SaleTemplateName = $value;
	}
/**
 *

 * @return SellingManagerProductDetailsType
 */
	function getSellingManagerProductDetails()
	{
		return $this->SellingManagerProductDetails;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setSellingManagerProductDetails($value)
	{
		$this->SellingManagerProductDetails = $value;
	}
/**
 *

 * @return FeesType
 */
	function getFees()
	{
		return $this->Fees;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setFees($value)
	{
		$this->Fees = $value;
	}
/**
 *

 * @return 
 */
	function AddSellingManagerTemplateResponseType()
	{
		$this->AbstractResponseType('AddSellingManagerTemplateResponseType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'CategoryID' =>
				array(
					'required' => false,
					'type' => 'long',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'Category2ID' =>
				array(
					'required' => false,
					'type' => 'long',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'SaleTemplateID' =>
				array(
					'required' => false,
					'type' => 'long',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'SaleTemplateGroupID' =>
				array(
					'required' => false,
					'type' => 'long',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'SaleTemplateName' =>
				array(
					'required' => false,
					'type' => 'string',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'SellingManagerProductDetails' =>
				array(
					'required' => false,
					'type' => 'SellingManagerProductDetailsType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'Fees' =>
				array(
					'required' => false,
					'type' => 'FeesType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				)
			));

	}
}
?>
