<?php
// autogenerated file 29.05.2009 15:17
// $Id: $
// $Log: $
//
//
require_once 'EbatNs_FacetType.php';

class AutomatedLeaveFeedbackEventCodeType extends EbatNs_FacetType
{
	// start props
	// @var string $PositiveFeedbackReceived
	var $PositiveFeedbackReceived = 'PositiveFeedbackReceived';
	// @var string $PaymentReceived
	var $PaymentReceived = 'PaymentReceived';
	// @var string $None
	var $None = 'None';
	// @var string $CustomCode
	var $CustomCode = 'CustomCode';
	// end props

/**
 *

 * @return 
 */
	function AutomatedLeaveFeedbackEventCodeType()
	{
		$this->EbatNs_FacetType('AutomatedLeaveFeedbackEventCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_AutomatedLeaveFeedbackEventCodeType = new AutomatedLeaveFeedbackEventCodeType();

?>
