<?php
// autogenerated file 29.05.2009 15:17
// $Id: $
// $Log: $
//
//
require_once 'EbatNs_FacetType.php';

class BalanceCodeType extends EbatNs_FacetType
{
	// start props
	// @var string $Other
	var $Other = 'Other';
	// @var string $CustomCode
	var $CustomCode = 'CustomCode';
	// end props

/**
 *

 * @return 
 */
	function BalanceCodeType()
	{
		$this->EbatNs_FacetType('BalanceCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_BalanceCodeType = new BalanceCodeType();

?>
