<?php
// autogenerated file 29.05.2009 15:17
// $Id: $
// $Log: $
//
//
require_once 'EbatNs_SimpleType.php';

class BidderIdType extends EbatNs_SimpleType
{
	// start props
	// end props

/**
 *

 * @return 
 */
	function BidderIdType()
	{
		$this->EbatNs_SimpleType('BidderIdType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_BidderIdType = new BidderIdType();

?>
