<?php
// autogenerated file 29.05.2009 15:17
// $Id: $
// $Log: $
//
//
require_once 'MaximumItemRequirementsType.php';
require_once 'VerifiedUserRequirementsType.php';
require_once 'EbatNs_ComplexType.php';
require_once 'MaximumBuyerPolicyViolationsType.php';
require_once 'MaximumUnpaidItemStrikesInfoType.php';

class BuyerRequirementDetailsType extends EbatNs_ComplexType
{
	// start props
	// @var boolean $ShipToRegistrationCountry
	var $ShipToRegistrationCountry;
	// @var boolean $ZeroFeedbackScore
	var $ZeroFeedbackScore;
	// @var int $MinimumFeedbackScore
	var $MinimumFeedbackScore;
	// @var MaximumItemRequirementsType $MaximumItemRequirements
	var $MaximumItemRequirements;
	// @var boolean $LinkedPayPalAccount
	var $LinkedPayPalAccount;
	// @var VerifiedUserRequirementsType $VerifiedUserRequirements
	var $VerifiedUserRequirements;
	// @var MaximumUnpaidItemStrikesInfoType $MaximumUnpaidItemStrikesInfo
	var $MaximumUnpaidItemStrikesInfo;
	// @var MaximumBuyerPolicyViolationsType $MaximumBuyerPolicyViolations
	var $MaximumBuyerPolicyViolations;
	// end props

/**
 *

 * @return boolean
 */
	function getShipToRegistrationCountry()
	{
		return $this->ShipToRegistrationCountry;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setShipToRegistrationCountry($value)
	{
		$this->ShipToRegistrationCountry = $value;
	}
/**
 *

 * @return boolean
 */
	function getZeroFeedbackScore()
	{
		return $this->ZeroFeedbackScore;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setZeroFeedbackScore($value)
	{
		$this->ZeroFeedbackScore = $value;
	}
/**
 *

 * @return int
 */
	function getMinimumFeedbackScore()
	{
		return $this->MinimumFeedbackScore;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setMinimumFeedbackScore($value)
	{
		$this->MinimumFeedbackScore = $value;
	}
/**
 *

 * @return MaximumItemRequirementsType
 */
	function getMaximumItemRequirements()
	{
		return $this->MaximumItemRequirements;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setMaximumItemRequirements($value)
	{
		$this->MaximumItemRequirements = $value;
	}
/**
 *

 * @return boolean
 */
	function getLinkedPayPalAccount()
	{
		return $this->LinkedPayPalAccount;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setLinkedPayPalAccount($value)
	{
		$this->LinkedPayPalAccount = $value;
	}
/**
 *

 * @return VerifiedUserRequirementsType
 */
	function getVerifiedUserRequirements()
	{
		return $this->VerifiedUserRequirements;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setVerifiedUserRequirements($value)
	{
		$this->VerifiedUserRequirements = $value;
	}
/**
 *

 * @return MaximumUnpaidItemStrikesInfoType
 */
	function getMaximumUnpaidItemStrikesInfo()
	{
		return $this->MaximumUnpaidItemStrikesInfo;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setMaximumUnpaidItemStrikesInfo($value)
	{
		$this->MaximumUnpaidItemStrikesInfo = $value;
	}
/**
 *

 * @return MaximumBuyerPolicyViolationsType
 */
	function getMaximumBuyerPolicyViolations()
	{
		return $this->MaximumBuyerPolicyViolations;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setMaximumBuyerPolicyViolations($value)
	{
		$this->MaximumBuyerPolicyViolations = $value;
	}
/**
 *

 * @return 
 */
	function BuyerRequirementDetailsType()
	{
		$this->EbatNs_ComplexType('BuyerRequirementDetailsType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'ShipToRegistrationCountry' =>
				array(
					'required' => false,
					'type' => 'boolean',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'ZeroFeedbackScore' =>
				array(
					'required' => false,
					'type' => 'boolean',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'MinimumFeedbackScore' =>
				array(
					'required' => false,
					'type' => 'int',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'MaximumItemRequirements' =>
				array(
					'required' => false,
					'type' => 'MaximumItemRequirementsType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'LinkedPayPalAccount' =>
				array(
					'required' => false,
					'type' => 'boolean',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'VerifiedUserRequirements' =>
				array(
					'required' => false,
					'type' => 'VerifiedUserRequirementsType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'MaximumUnpaidItemStrikesInfo' =>
				array(
					'required' => false,
					'type' => 'MaximumUnpaidItemStrikesInfoType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'MaximumBuyerPolicyViolations' =>
				array(
					'required' => false,
					'type' => 'MaximumBuyerPolicyViolationsType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				)
			));

	}
}
?>
