<?php
// autogenerated file 29.05.2009 15:17
// $Id: $
// $Log: $
//
//
require_once 'EbatNs_FacetType.php';

class BuyerPaymentMethodCodeType extends EbatNs_FacetType
{
	// start props
	// @var string $None
	var $None = 'None';
	// @var string $MOCC
	var $MOCC = 'MOCC';
	// @var string $AmEx
	var $AmEx = 'AmEx';
	// @var string $PaymentSeeDescription
	var $PaymentSeeDescription = 'PaymentSeeDescription';
	// @var string $CCAccepted
	var $CCAccepted = 'CCAccepted';
	// @var string $PersonalCheck
	var $PersonalCheck = 'PersonalCheck';
	// @var string $COD
	var $COD = 'COD';
	// @var string $VisaMC
	var $VisaMC = 'VisaMC';
	// @var string $PaisaPayAccepted
	var $PaisaPayAccepted = 'PaisaPayAccepted';
	// @var string $Other
	var $Other = 'Other';
	// @var string $PayPal
	var $PayPal = 'PayPal';
	// @var string $Discover
	var $Discover = 'Discover';
	// @var string $CashOnPickup
	var $CashOnPickup = 'CashOnPickup';
	// @var string $MoneyXferAccepted
	var $MoneyXferAccepted = 'MoneyXferAccepted';
	// @var string $MoneyXferAcceptedInCheckout
	var $MoneyXferAcceptedInCheckout = 'MoneyXferAcceptedInCheckout';
	// @var string $OtherOnlinePayments
	var $OtherOnlinePayments = 'OtherOnlinePayments';
	// @var string $Escrow
	var $Escrow = 'Escrow';
	// @var string $PrePayDelivery
	var $PrePayDelivery = 'PrePayDelivery';
	// @var string $CODPrePayDelivery
	var $CODPrePayDelivery = 'CODPrePayDelivery';
	// @var string $PostalTransfer
	var $PostalTransfer = 'PostalTransfer';
	// @var string $CustomCode
	var $CustomCode = 'CustomCode';
	// @var string $LoanCheck
	var $LoanCheck = 'LoanCheck';
	// @var string $CashInPerson
	var $CashInPerson = 'CashInPerson';
	// @var string $ELV
	var $ELV = 'ELV';
	// @var string $PaisaPayEscrow
	var $PaisaPayEscrow = 'PaisaPayEscrow';
	// @var string $PaisaPayEscrowEMI
	var $PaisaPayEscrowEMI = 'PaisaPayEscrowEMI';
	// @var string $IntegratedMerchantCreditCard
	var $IntegratedMerchantCreditCard = 'IntegratedMerchantCreditCard';
	// @var string $Moneybookers
	var $Moneybookers = 'Moneybookers';
	// @var string $Paymate
	var $Paymate = 'Paymate';
	// @var string $ProPay
	var $ProPay = 'ProPay';
	// @var string $PayOnPickup
	var $PayOnPickup = 'PayOnPickup';
	// end props

/**
 *

 * @return 
 */
	function BuyerPaymentMethodCodeType()
	{
		$this->EbatNs_FacetType('BuyerPaymentMethodCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_BuyerPaymentMethodCodeType = new BuyerPaymentMethodCodeType();

?>
