<?php
// autogenerated file 29.05.2009 15:17
// $Id: $
// $Log: $
//
//
require_once 'EbatNs_ComplexType.php';
require_once 'BuyerSatisfactionStatusCodeType.php';
require_once 'SellerDashboardAlertType.php';

class BuyerSatisfactionDashboardType extends EbatNs_ComplexType
{
	// start props
	// @var BuyerSatisfactionStatusCodeType $Status
	var $Status;
	// @var SellerDashboardAlertType $Alert
	var $Alert;
	// end props

/**
 *

 * @return BuyerSatisfactionStatusCodeType
 */
	function getStatus()
	{
		return $this->Status;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setStatus($value)
	{
		$this->Status = $value;
	}
/**
 *

 * @return SellerDashboardAlertType
 * @param  $index 
 */
	function getAlert($index = null)
	{
		if ($index) {
		return $this->Alert[$index];
	} else {
		return $this->Alert;
	}

	}
/**
 *

 * @return void
 * @param  $value 
 * @param  $index 
 */
	function setAlert($value, $index = null)
	{
		if ($index) {
	$this->Alert[$index] = $value;
	} else {
	$this->Alert = $value;
	}

	}
/**
 *

 * @return 
 */
	function BuyerSatisfactionDashboardType()
	{
		$this->EbatNs_ComplexType('BuyerSatisfactionDashboardType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'Status' =>
				array(
					'required' => false,
					'type' => 'BuyerSatisfactionStatusCodeType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'Alert' =>
				array(
					'required' => false,
					'type' => 'SellerDashboardAlertType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => true,
					'cardinality' => '0..*'
				)
			));

	}
}
?>
