<?php
// autogenerated file 29.05.2009 15:17
// $Id: $
// $Log: $
//
//
require_once 'EbatNs_ComplexType.php';

class BuyerRoleMetricsType extends EbatNs_ComplexType
{
	// start props
	// @var int $PositiveFeedbackLeftCount
	var $PositiveFeedbackLeftCount;
	// @var int $NegativeFeedbackLeftCount
	var $NegativeFeedbackLeftCount;
	// @var int $NeutralFeedbackLeftCount
	var $NeutralFeedbackLeftCount;
	// @var float $FeedbackLeftPercent
	var $FeedbackLeftPercent;
	// end props

/**
 *

 * @return int
 */
	function getPositiveFeedbackLeftCount()
	{
		return $this->PositiveFeedbackLeftCount;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setPositiveFeedbackLeftCount($value)
	{
		$this->PositiveFeedbackLeftCount = $value;
	}
/**
 *

 * @return int
 */
	function getNegativeFeedbackLeftCount()
	{
		return $this->NegativeFeedbackLeftCount;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setNegativeFeedbackLeftCount($value)
	{
		$this->NegativeFeedbackLeftCount = $value;
	}
/**
 *

 * @return int
 */
	function getNeutralFeedbackLeftCount()
	{
		return $this->NeutralFeedbackLeftCount;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setNeutralFeedbackLeftCount($value)
	{
		$this->NeutralFeedbackLeftCount = $value;
	}
/**
 *

 * @return float
 */
	function getFeedbackLeftPercent()
	{
		return $this->FeedbackLeftPercent;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setFeedbackLeftPercent($value)
	{
		$this->FeedbackLeftPercent = $value;
	}
/**
 *

 * @return 
 */
	function BuyerRoleMetricsType()
	{
		$this->EbatNs_ComplexType('BuyerRoleMetricsType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'PositiveFeedbackLeftCount' =>
				array(
					'required' => false,
					'type' => 'int',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'NegativeFeedbackLeftCount' =>
				array(
					'required' => false,
					'type' => 'int',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'NeutralFeedbackLeftCount' =>
				array(
					'required' => false,
					'type' => 'int',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'FeedbackLeftPercent' =>
				array(
					'required' => false,
					'type' => 'float',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				)
			));

	}
}
?>
