<?php
// autogenerated file 29.05.2009 15:17
// $Id: $
// $Log: $
//
//
require_once 'EbatNs_FacetType.php';

class BuyerSatisfactionStatusCodeType extends EbatNs_FacetType
{
	// start props
	// @var string $Excellent
	var $Excellent = 'Excellent';
	// @var string $Good
	var $Good = 'Good';
	// @var string $NeedsWork
	var $NeedsWork = 'NeedsWork';
	// @var string $Poor
	var $Poor = 'Poor';
	// @var string $VeryPoor
	var $VeryPoor = 'VeryPoor';
	// @var string $Unacceptable
	var $Unacceptable = 'Unacceptable';
	// @var string $CustomCode
	var $CustomCode = 'CustomCode';
	// end props

/**
 *

 * @return 
 */
	function BuyerSatisfactionStatusCodeType()
	{
		$this->EbatNs_FacetType('BuyerSatisfactionStatusCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_BuyerSatisfactionStatusCodeType = new BuyerSatisfactionStatusCodeType();

?>
