<?php
// autogenerated file 29.05.2009 15:17
// $Id: $
// $Log: $
//
//
require_once 'CharityAffiliationTypeCodeType.php';
require_once 'EbatNs_ComplexType.php';

class CharityAffiliationDetailType extends EbatNs_ComplexType
{
	// start props
	// @var string $CharityID
	var $CharityID;
	// @var CharityAffiliationTypeCodeType $AffiliationType
	var $AffiliationType;
	// @var dateTime $LastUsedTime
	var $LastUsedTime;
	// end props

/**
 *

 * @return string
 */
	function getCharityID()
	{
		return $this->CharityID;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setCharityID($value)
	{
		$this->CharityID = $value;
	}
/**
 *

 * @return CharityAffiliationTypeCodeType
 */
	function getAffiliationType()
	{
		return $this->AffiliationType;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setAffiliationType($value)
	{
		$this->AffiliationType = $value;
	}
/**
 *

 * @return dateTime
 */
	function getLastUsedTime()
	{
		return $this->LastUsedTime;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setLastUsedTime($value)
	{
		$this->LastUsedTime = $value;
	}
/**
 *

 * @return 
 */
	function CharityAffiliationDetailType()
	{
		$this->EbatNs_ComplexType('CharityAffiliationDetailType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'CharityID' =>
				array(
					'required' => false,
					'type' => 'string',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'AffiliationType' =>
				array(
					'required' => false,
					'type' => 'CharityAffiliationTypeCodeType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'LastUsedTime' =>
				array(
					'required' => false,
					'type' => 'dateTime',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				)
			));

	}
}
?>
