<?php
// autogenerated file 29.05.2009 15:17
// $Id: $
// $Log: $
//
//
require_once 'CharityAffiliationDetailType.php';
require_once 'EbatNs_ComplexType.php';

class CharityAffiliationDetailsType extends EbatNs_ComplexType
{
	// start props
	// @var CharityAffiliationDetailType $CharityAffiliationDetail
	var $CharityAffiliationDetail;
	// end props

/**
 *

 * @return CharityAffiliationDetailType
 * @param  $index 
 */
	function getCharityAffiliationDetail($index = null)
	{
		if ($index) {
		return $this->CharityAffiliationDetail[$index];
	} else {
		return $this->CharityAffiliationDetail;
	}

	}
/**
 *

 * @return void
 * @param  $value 
 * @param  $index 
 */
	function setCharityAffiliationDetail($value, $index = null)
	{
		if ($index) {
	$this->CharityAffiliationDetail[$index] = $value;
	} else {
	$this->CharityAffiliationDetail = $value;
	}

	}
/**
 *

 * @return 
 */
	function CharityAffiliationDetailsType()
	{
		$this->EbatNs_ComplexType('CharityAffiliationDetailsType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'CharityAffiliationDetail' =>
				array(
					'required' => false,
					'type' => 'CharityAffiliationDetailType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => true,
					'cardinality' => '0..*'
				)
			));

	}
}
?>
