<?php
// autogenerated file 29.05.2009 15:17
// $Id: $
// $Log: $
//
//
require_once 'EbatNs_FacetType.php';

class DayOfWeekCodeType extends EbatNs_FacetType
{
	// start props
	// @var string $Sunday
	var $Sunday = 'Sunday';
	// @var string $Monday
	var $Monday = 'Monday';
	// @var string $Tuesday
	var $Tuesday = 'Tuesday';
	// @var string $Wednesday
	var $Wednesday = 'Wednesday';
	// @var string $Thursday
	var $Thursday = 'Thursday';
	// @var string $Friday
	var $Friday = 'Friday';
	// @var string $Saturday
	var $Saturday = 'Saturday';
	// @var string $CustomCode
	var $CustomCode = 'CustomCode';
	// end props

/**
 *

 * @return 
 */
	function DayOfWeekCodeType()
	{
		$this->EbatNs_FacetType('DayOfWeekCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_DayOfWeekCodeType = new DayOfWeekCodeType();

?>
