<?php
// autogenerated file 29.05.2009 15:17
// $Id: $
// $Log: $
//
//
require_once 'EbatNs_FacetType.php';

class DetailLevelCodeType extends EbatNs_FacetType
{
	// start props
	// @var string $ReturnAll
	var $ReturnAll = 'ReturnAll';
	// @var string $ItemReturnDescription
	var $ItemReturnDescription = 'ItemReturnDescription';
	// @var string $ItemReturnAttributes
	var $ItemReturnAttributes = 'ItemReturnAttributes';
	// @var string $ItemReturnCategories
	var $ItemReturnCategories = 'ItemReturnCategories';
	// @var string $ReturnSummary
	var $ReturnSummary = 'ReturnSummary';
	// @var string $ReturnHeaders
	var $ReturnHeaders = 'ReturnHeaders';
	// @var string $ReturnMessages
	var $ReturnMessages = 'ReturnMessages';
	// end props

/**
 *

 * @return 
 */
	function DetailLevelCodeType()
	{
		$this->EbatNs_FacetType('DetailLevelCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_DetailLevelCodeType = new DetailLevelCodeType();

?>
