<?php
// autogenerated file 29.05.2009 15:17
// $Id: $
// $Log: $
//
//
require_once 'EbatNs_FacetType.php';

class DeviceTypeCodeType extends EbatNs_FacetType
{
	// start props
	// @var string $Platform
	var $Platform = 'Platform';
	// @var string $SMS
	var $SMS = 'SMS';
	// @var string $ClientAlerts
	var $ClientAlerts = 'ClientAlerts';
	// @var string $CustomCode
	var $CustomCode = 'CustomCode';
	// end props

/**
 *

 * @return 
 */
	function DeviceTypeCodeType()
	{
		$this->EbatNs_FacetType('DeviceTypeCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_DeviceTypeCodeType = new DeviceTypeCodeType();

?>
