<?php
// autogenerated file 29.05.2009 15:17
// $Id: $
// $Log: $
//
//
require_once 'EbatNs_SimpleType.php';

class DisputeIDType extends EbatNs_SimpleType
{
	// start props
	// end props

/**
 *

 * @return 
 */
	function DisputeIDType()
	{
		$this->EbatNs_SimpleType('DisputeIDType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_DisputeIDType = new DisputeIDType();

?>
