<?php
// autogenerated file 29.05.2009 15:17
// $Id: $
// $Log: $
//
//
require_once 'EbatNs_FacetType.php';

class DisputeFilterTypeCodeType extends EbatNs_FacetType
{
	// start props
	// @var string $AllInvolvedDisputes
	var $AllInvolvedDisputes = 'AllInvolvedDisputes';
	// @var string $DisputesAwaitingMyResponse
	var $DisputesAwaitingMyResponse = 'DisputesAwaitingMyResponse';
	// @var string $DisputesAwaitingOtherPartyResponse
	var $DisputesAwaitingOtherPartyResponse = 'DisputesAwaitingOtherPartyResponse';
	// @var string $AllInvolvedClosedDisputes
	var $AllInvolvedClosedDisputes = 'AllInvolvedClosedDisputes';
	// @var string $EligibleForCredit
	var $EligibleForCredit = 'EligibleForCredit';
	// @var string $UnpaidItemDisputes
	var $UnpaidItemDisputes = 'UnpaidItemDisputes';
	// @var string $ItemNotReceivedDisputes
	var $ItemNotReceivedDisputes = 'ItemNotReceivedDisputes';
	// @var string $CustomCode
	var $CustomCode = 'CustomCode';
	// end props

/**
 *

 * @return 
 */
	function DisputeFilterTypeCodeType()
	{
		$this->EbatNs_FacetType('DisputeFilterTypeCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_DisputeFilterTypeCodeType = new DisputeFilterTypeCodeType();

?>
