<?php
// autogenerated file 29.05.2009 15:17
// $Id: $
// $Log: $
//
//
require_once 'EbatNs_ComplexType.php';

class eBayMotorsProShippingMethodEnabledDefinitionType extends EbatNs_ComplexType
{
	// start props
	// end props

/**
 *

 * @return 
 */
	function eBayMotorsProShippingMethodEnabledDefinitionType()
	{
		$this->EbatNs_ComplexType('eBayMotorsProShippingMethodEnabledDefinitionType', 'urn:ebay:apis:eBLBaseComponents');

	}
}
?>
