<?php
// autogenerated file 29.05.2009 15:17
// $Id: $
// $Log: $
//
//
require_once 'EbatNs_FacetType.php';

class EnableCodeType extends EbatNs_FacetType
{
	// start props
	// @var string $Enable
	var $Enable = 'Enable';
	// @var string $Disable
	var $Disable = 'Disable';
	// @var string $CustomCode
	var $CustomCode = 'CustomCode';
	// end props

/**
 *

 * @return 
 */
	function EnableCodeType()
	{
		$this->EbatNs_FacetType('EnableCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_EnableCodeType = new EnableCodeType();

?>
