<?php
// autogenerated file 29.05.2009 15:17
// $Id: $
// $Log: $
//
//
require_once 'EndReasonCodeType.php';
require_once 'EbatNs_ComplexType.php';
require_once 'ItemIDType.php';

class EndItemRequestContainerType extends EbatNs_ComplexType
{
	// start props
	// @var ItemIDType $ItemID
	var $ItemID;
	// @var EndReasonCodeType $EndingReason
	var $EndingReason;
	// @var string $MessageID
	var $MessageID;
	// end props

/**
 *

 * @return ItemIDType
 */
	function getItemID()
	{
		return $this->ItemID;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setItemID($value)
	{
		$this->ItemID = $value;
	}
/**
 *

 * @return EndReasonCodeType
 */
	function getEndingReason()
	{
		return $this->EndingReason;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setEndingReason($value)
	{
		$this->EndingReason = $value;
	}
/**
 *

 * @return string
 */
	function getMessageID()
	{
		return $this->MessageID;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setMessageID($value)
	{
		$this->MessageID = $value;
	}
/**
 *

 * @return 
 */
	function EndItemRequestContainerType()
	{
		$this->EbatNs_ComplexType('EndItemRequestContainerType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'ItemID' =>
				array(
					'required' => false,
					'type' => 'ItemIDType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'EndingReason' =>
				array(
					'required' => false,
					'type' => 'EndReasonCodeType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'MessageID' =>
				array(
					'required' => false,
					'type' => 'string',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				)
			));

	}
}
?>
