<?php
// autogenerated file 29.05.2009 15:17
// $Id: $
// $Log: $
//
//
require_once 'ErrorType.php';
require_once 'EbatNs_ComplexType.php';

class EndItemResponseContainerType extends EbatNs_ComplexType
{
	// start props
	// @var dateTime $EndTime
	var $EndTime;
	// @var string $CorrelationID
	var $CorrelationID;
	// @var ErrorType $Errors
	var $Errors;
	// end props

/**
 *

 * @return dateTime
 */
	function getEndTime()
	{
		return $this->EndTime;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setEndTime($value)
	{
		$this->EndTime = $value;
	}
/**
 *

 * @return string
 */
	function getCorrelationID()
	{
		return $this->CorrelationID;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setCorrelationID($value)
	{
		$this->CorrelationID = $value;
	}
/**
 *

 * @return ErrorType
 * @param  $index 
 */
	function getErrors($index = null)
	{
		if ($index) {
		return $this->Errors[$index];
	} else {
		return $this->Errors;
	}

	}
/**
 *

 * @return void
 * @param  $value 
 * @param  $index 
 */
	function setErrors($value, $index = null)
	{
		if ($index) {
	$this->Errors[$index] = $value;
	} else {
	$this->Errors = $value;
	}

	}
/**
 *

 * @return 
 */
	function EndItemResponseContainerType()
	{
		$this->EbatNs_ComplexType('EndItemResponseContainerType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'EndTime' =>
				array(
					'required' => false,
					'type' => 'dateTime',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'CorrelationID' =>
				array(
					'required' => false,
					'type' => 'string',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'Errors' =>
				array(
					'required' => false,
					'type' => 'ErrorType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => true,
					'cardinality' => '0..*'
				)
			));

	}
}
?>
