<?php
// autogenerated file 29.05.2009 15:17
// $Id: $
// $Log: $
//
//
require_once 'EndItemRequestContainerType.php';
require_once 'AbstractRequestType.php';

class EndItemsRequestType extends AbstractRequestType
{
	// start props
	// @var EndItemRequestContainerType $EndItemRequestContainer
	var $EndItemRequestContainer;
	// end props

/**
 *

 * @return EndItemRequestContainerType
 * @param  $index 
 */
	function getEndItemRequestContainer($index = null)
	{
		if ($index) {
		return $this->EndItemRequestContainer[$index];
	} else {
		return $this->EndItemRequestContainer;
	}

	}
/**
 *

 * @return void
 * @param  $value 
 * @param  $index 
 */
	function setEndItemRequestContainer($value, $index = null)
	{
		if ($index) {
	$this->EndItemRequestContainer[$index] = $value;
	} else {
	$this->EndItemRequestContainer = $value;
	}

	}
/**
 *

 * @return 
 */
	function EndItemsRequestType()
	{
		$this->AbstractRequestType('EndItemsRequestType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'EndItemRequestContainer' =>
				array(
					'required' => false,
					'type' => 'EndItemRequestContainerType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => true,
					'cardinality' => '0..*'
				)
			));

	}
}
?>
