<?php
// autogenerated file 29.05.2009 15:17
// $Id: $
// $Log: $
//
//
require_once 'PayPalRequiredForStoreOwnerDefinitionType.php';
require_once 'PaisaPayFullEscrowEnabledDefinitionType.php';
require_once 'ProPackEnabledDefinitionType.php';
require_once 'ListingDurationDefinitionsType.php';
require_once 'ItemSpecificsEnabledDefinitionType.php';
require_once 'eBayMotorsProSellerContactDetailsEnabledDefinitionType.php';
require_once 'LocalMarketBestOfferEnabledDefinitionType.php';
require_once 'LocalListingDistancesSpecialtyDefinitionType.php';
require_once 'HomePageFeaturedEnabledDefinitionType.php';
require_once 'AdFormatEnabledDefinitionType.php';
require_once 'ClassifiedAdPhoneCountDefinitionType.php';
require_once 'PaymentMethodDefinitionType.php';
require_once 'ClassifiedAdShippingMethodEnabledDefinitionType.php';
require_once 'ClassifiedAdAutoDeclineEnabledDefinitionType.php';
require_once 'FreePicturePackEnabledDefinitionType.php';
require_once 'LocalMarketPhoneCountDefinitionType.php';
require_once 'ExpressPicturesRequiredDefinitionType.php';
require_once 'eBayMotorsProCounterOfferEnabledDefinitionType.php';
require_once 'ClassifiedAdPaymentMethodEnabledDefinitionType.php';
require_once 'SkypeMeNonTransactionalEnabledDefinitionType.php';
require_once 'LocalMarketAdFormatEnabledDefinitionType.php';
require_once 'ReturnPolicyEnabledDefinitionType.php';
require_once 'ClassifiedAdContactByAddressEnabledDefinitionType.php';
require_once 'LocalMarketContactByEmailEnabledDefinitionType.php';
require_once 'ReviseQuantityAllowedDefinitionType.php';
require_once 'eBayMotorsProPaymentMethodCheckOutEnabledDefinitionType.php';
require_once 'BasicUpgradePackEnabledDefinitionType.php';
require_once 'eBayMotorsProAutoAcceptEnabledDefinitionType.php';
require_once 'LocalMarketCounterOfferEnabledDefinitionType.php';
require_once 'VariationsEnabledDefinitionType.php';
require_once 'INEscrowWorkflowTimelineDefinitionType.php';
require_once 'MaxFlatShippingCostCBTExemptDefinitionType.php';
require_once 'LocalMarketAutoAcceptEnabledDefinitionType.php';
require_once 'ClassifiedAdCounterOfferEnabledDefinitionType.php';
require_once 'eBayMotorsProStreetCountDefinitionType.php';
require_once 'eBayMotorsProContactByEmailEnabledDefinitionType.php';
require_once 'eBayMotorsProAutoDeclineEnabledDefinitionType.php';
require_once 'LocalMarketRegularSubscriptionDefinitionType.php';
require_once 'eBayMotorsProPhoneCountDefinitionType.php';
require_once 'ExpressEnabledDefinitionType.php';
require_once 'LocalMarketCompanyNameEnabledDefinitionType.php';
require_once 'LocalMarketShippingMethodEnabledDefinitionType.php';
require_once 'eBayMotorsProContactByAddressEnabledDefinitionType.php';
require_once 'HandlingTimeEnabledDefinitionType.php';
require_once 'PremiumSubscriptionDefinitionType.php';
require_once 'MinimumReservePriceDefinitionType.php';
require_once 'LocalMarketAutoDeclineEnabledDefinitionType.php';
require_once 'Group3MaxFlatShippingCostDefinitionType.php';
require_once 'SkypeMeTransactionalEnabledDefinitionType.php';
require_once 'eBayMotorsProAdFormatEnabledDefinitionType.php';
require_once 'ListingEnhancementDurationDefinitionType.php';
require_once 'SellerContactDetailsEnabledDefinitionType.php';
require_once 'ShippingTermRequiredDefinitionType.php';
require_once 'NonSubscriptionDefinitionType.php';
require_once 'eBayMotorsProContactByPhoneEnabledDefinitionType.php';
require_once 'AttributeConversionEnabledFeatureDefinitionType.php';
require_once 'StoreInventoryEnabledDefinitionType.php';
require_once 'SafePaymentRequiredDefinitionType.php';
require_once 'LocalListingDistancesRegularDefinitionType.php';
require_once 'UserConsentRequiredDefinitionType.php';
require_once 'BestOfferAutoDeclineEnabledDefinitionType.php';
require_once 'ExpressConditionRequiredDefinitionType.php';
require_once 'LocalMarketContactByAddressEnabledDefinitionType.php';
require_once 'BestOfferCounterEnabledDefinitionType.php';
require_once 'LocalMarketStreetCountDefinitionType.php';
require_once 'RevisePriceAllowedDefinitionType.php';
require_once 'LocalMarketPaymentMethodCheckOutEnabledDefinitionType.php';
require_once 'LocalMarketSellerContactDetailsEnabledDefinitionType.php';
require_once 'EbatNs_ComplexType.php';
require_once 'LocalMarketNonSubscriptionDefinitionType.php';
require_once 'eBayMotorsProBestOfferEnabledDefinitionType.php';
require_once 'ProPackPlusEnabledDefinitionType.php';
require_once 'BuyerGuaranteeEnabledDefinitionType.php';
require_once 'eBayMotorsProCompanyNameEnabledDefinitionType.php';
require_once 'LocalMarketSpecialitySubscriptionDefinitionType.php';
require_once 'MaxFlatShippingCostDefinitionType.php';
require_once 'PayPalBuyerProtectionEnabledDefinitionType.php';
require_once 'DutchBINEnabledDefinitionType.php';
require_once 'CombinedFixedPriceTreatmentEnabledDefinitionType.php';
require_once 'PayPalRequiredDefinitionType.php';
require_once 'ClassifiedAdBestOfferEnabledDefinitionType.php';
require_once 'ClassifiedAdStreetCountDefinitionType.php';
require_once 'StoreOwnerExtendedListingDurationsDefinitionType.php';
require_once 'TCREnabledDefinitionType.php';
require_once 'LocalMarketContactByPhoneEnabledDefinitionType.php';
require_once 'CrossBorderTradeAustraliaEnabledDefinitionType.php';
require_once 'CrossBorderTradeGBEnabledDefinitionType.php';
require_once 'Group2MaxFlatShippingCostDefinitionType.php';
require_once 'ClassifiedAdPayPerLeadEnabledDefinitionType.php';
require_once 'ValuePackEnabledDefinitionType.php';
require_once 'FreeGalleryPlusEnabledDefinitionType.php';
require_once 'ClassifiedAdContactByPhoneEnabledDefinitionType.php';
require_once 'LocalListingDistancesNonSubscriptionDefinitionType.php';
require_once 'ClassifiedAdCompanyNameEnabledDefinitionType.php';
require_once 'CrossBorderTradeNorthAmericaEnabledDefinitionType.php';
require_once 'eBayMotorsProShippingMethodEnabledDefinitionType.php';
require_once 'SpecialitySubscriptionDefinitionType.php';
require_once 'StoreOwnerExtendedListingDurationsEnabledDefinitionType.php';
require_once 'Group1MaxFlatShippingCostDefinitionType.php';
require_once 'BestOfferAutoAcceptEnabledDefinitionType.php';
require_once 'ClassifiedAdContactByEmailEnabledDefintionType.php';
require_once 'ClassifiedAdAutoAcceptEnabledDefinitionType.php';
require_once 'BestOfferEnabledDefinitionType.php';
require_once 'LocalMarketPremiumSubscriptionDefinitionType.php';
require_once 'RegularSubscriptionDefinitionType.php';

class FeatureDefinitionsType extends EbatNs_ComplexType
{
	// start props
	// @var ListingDurationDefinitionsType $ListingDurations
	var $ListingDurations;
	// @var ShippingTermRequiredDefinitionType $ShippingTermsRequired
	var $ShippingTermsRequired;
	// @var BestOfferEnabledDefinitionType $BestOfferEnabled
	var $BestOfferEnabled;
	// @var DutchBINEnabledDefinitionType $DutchBINEnabled
	var $DutchBINEnabled;
	// @var UserConsentRequiredDefinitionType $UserConsentRequired
	var $UserConsentRequired;
	// @var HomePageFeaturedEnabledDefinitionType $HomePageFeaturedEnabled
	var $HomePageFeaturedEnabled;
	// @var ProPackEnabledDefinitionType $ProPackEnabled
	var $ProPackEnabled;
	// @var BasicUpgradePackEnabledDefinitionType $BasicUpgradePackEnabled
	var $BasicUpgradePackEnabled;
	// @var ValuePackEnabledDefinitionType $ValuePackEnabled
	var $ValuePackEnabled;
	// @var ProPackPlusEnabledDefinitionType $ProPackPlusEnabled
	var $ProPackPlusEnabled;
	// @var AdFormatEnabledDefinitionType $AdFormatEnabled
	var $AdFormatEnabled;
	// @var BestOfferCounterEnabledDefinitionType $BestOfferCounterEnabled
	var $BestOfferCounterEnabled;
	// @var BestOfferAutoDeclineEnabledDefinitionType $BestOfferAutoDeclineEnabled
	var $BestOfferAutoDeclineEnabled;
	// @var LocalMarketSpecialitySubscriptionDefinitionType $LocalMarketSpecialitySubscription
	var $LocalMarketSpecialitySubscription;
	// @var LocalMarketRegularSubscriptionDefinitionType $LocalMarketRegularSubscription
	var $LocalMarketRegularSubscription;
	// @var LocalMarketPremiumSubscriptionDefinitionType $LocalMarketPremiumSubscription
	var $LocalMarketPremiumSubscription;
	// @var LocalMarketNonSubscriptionDefinitionType $LocalMarketNonSubscription
	var $LocalMarketNonSubscription;
	// @var ExpressEnabledDefinitionType $ExpressEnabled
	var $ExpressEnabled;
	// @var ExpressPicturesRequiredDefinitionType $ExpressPicturesRequired
	var $ExpressPicturesRequired;
	// @var ExpressConditionRequiredDefinitionType $ExpressConditionRequired
	var $ExpressConditionRequired;
	// @var MinimumReservePriceDefinitionType $MinimumReservePrice
	var $MinimumReservePrice;
	// @var TCREnabledDefinitionType $TransactionConfirmationRequestEnabled
	var $TransactionConfirmationRequestEnabled;
	// @var SellerContactDetailsEnabledDefinitionType $SellerContactDetailsEnabled
	var $SellerContactDetailsEnabled;
	// @var StoreInventoryEnabledDefinitionType $StoreInventoryEnabled
	var $StoreInventoryEnabled;
	// @var SkypeMeTransactionalEnabledDefinitionType $SkypeMeTransactionalEnabled
	var $SkypeMeTransactionalEnabled;
	// @var SkypeMeNonTransactionalEnabledDefinitionType $SkypeMeNonTransactionalEnabled
	var $SkypeMeNonTransactionalEnabled;
	// @var LocalListingDistancesRegularDefinitionType $LocalListingDistancesRegular
	var $LocalListingDistancesRegular;
	// @var LocalListingDistancesSpecialtyDefinitionType $LocalListingDistancesSpecialty
	var $LocalListingDistancesSpecialty;
	// @var LocalListingDistancesNonSubscriptionDefinitionType $LocalListingDistancesNonSubscription
	var $LocalListingDistancesNonSubscription;
	// @var ClassifiedAdPaymentMethodEnabledDefinitionType $ClassifiedAdPaymentMethodEnabled
	var $ClassifiedAdPaymentMethodEnabled;
	// @var ClassifiedAdShippingMethodEnabledDefinitionType $ClassifiedAdShippingMethodEnabled
	var $ClassifiedAdShippingMethodEnabled;
	// @var ClassifiedAdBestOfferEnabledDefinitionType $ClassifiedAdBestOfferEnabled
	var $ClassifiedAdBestOfferEnabled;
	// @var ClassifiedAdCounterOfferEnabledDefinitionType $ClassifiedAdCounterOfferEnabled
	var $ClassifiedAdCounterOfferEnabled;
	// @var ClassifiedAdAutoDeclineEnabledDefinitionType $ClassifiedAdAutoDeclineEnabled
	var $ClassifiedAdAutoDeclineEnabled;
	// @var ClassifiedAdContactByPhoneEnabledDefinitionType $ClassifiedAdContactByPhoneEnabled
	var $ClassifiedAdContactByPhoneEnabled;
	// @var ClassifiedAdContactByEmailEnabledDefintionType $ClassifiedAdContactByEmailEnabled
	var $ClassifiedAdContactByEmailEnabled;
	// @var SafePaymentRequiredDefinitionType $SafePaymentRequired
	var $SafePaymentRequired;
	// @var ClassifiedAdPayPerLeadEnabledDefinitionType $ClassifiedAdPayPerLeadEnabled
	var $ClassifiedAdPayPerLeadEnabled;
	// @var ItemSpecificsEnabledDefinitionType $ItemSpecificsEnabled
	var $ItemSpecificsEnabled;
	// @var PaisaPayFullEscrowEnabledDefinitionType $PaisaPayFullEscrowEnabled
	var $PaisaPayFullEscrowEnabled;
	// @var BestOfferAutoAcceptEnabledDefinitionType $BestOfferAutoAcceptEnabled
	var $BestOfferAutoAcceptEnabled;
	// @var ClassifiedAdAutoAcceptEnabledDefinitionType $ClassifiedAdAutoAcceptEnabled
	var $ClassifiedAdAutoAcceptEnabled;
	// @var CrossBorderTradeNorthAmericaEnabledDefinitionType $CrossBorderTradeNorthAmericaEnabled
	var $CrossBorderTradeNorthAmericaEnabled;
	// @var CrossBorderTradeGBEnabledDefinitionType $CrossBorderTradeGBEnabled
	var $CrossBorderTradeGBEnabled;
	// @var CrossBorderTradeAustraliaEnabledDefinitionType $CrossBorderTradeAustraliaEnabled
	var $CrossBorderTradeAustraliaEnabled;
	// @var PayPalBuyerProtectionEnabledDefinitionType $PayPalBuyerProtectionEnabled
	var $PayPalBuyerProtectionEnabled;
	// @var BuyerGuaranteeEnabledDefinitionType $BuyerGuaranteeEnabled
	var $BuyerGuaranteeEnabled;
	// @var CombinedFixedPriceTreatmentEnabledDefinitionType $CombinedFixedPriceTreatmentEnabled
	var $CombinedFixedPriceTreatmentEnabled;
	// @var ListingEnhancementDurationDefinitionType $GalleryFeaturedDurations
	var $GalleryFeaturedDurations;
	// @var INEscrowWorkflowTimelineDefinitionType $INEscrowWorkflowTimeline
	var $INEscrowWorkflowTimeline;
	// @var PayPalRequiredDefinitionType $PayPalRequired
	var $PayPalRequired;
	// @var eBayMotorsProAdFormatEnabledDefinitionType $eBayMotorsProAdFormatEnabled
	var $eBayMotorsProAdFormatEnabled;
	// @var eBayMotorsProContactByPhoneEnabledDefinitionType $eBayMotorsProContactByPhoneEnabled
	var $eBayMotorsProContactByPhoneEnabled;
	// @var eBayMotorsProPhoneCountDefinitionType $eBayMotorsProPhoneCount
	var $eBayMotorsProPhoneCount;
	// @var eBayMotorsProContactByAddressEnabledDefinitionType $eBayMotorsProContactByAddressEnabled
	var $eBayMotorsProContactByAddressEnabled;
	// @var eBayMotorsProStreetCountDefinitionType $eBayMotorsProStreetCount
	var $eBayMotorsProStreetCount;
	// @var eBayMotorsProCompanyNameEnabledDefinitionType $eBayMotorsProCompanyNameEnabled
	var $eBayMotorsProCompanyNameEnabled;
	// @var eBayMotorsProContactByEmailEnabledDefinitionType $eBayMotorsProContactByEmailEnabled
	var $eBayMotorsProContactByEmailEnabled;
	// @var eBayMotorsProBestOfferEnabledDefinitionType $eBayMotorsProBestOfferEnabled
	var $eBayMotorsProBestOfferEnabled;
	// @var eBayMotorsProAutoAcceptEnabledDefinitionType $eBayMotorsProAutoAcceptEnabled
	var $eBayMotorsProAutoAcceptEnabled;
	// @var eBayMotorsProAutoDeclineEnabledDefinitionType $eBayMotorsProAutoDeclineEnabled
	var $eBayMotorsProAutoDeclineEnabled;
	// @var eBayMotorsProPaymentMethodCheckOutEnabledDefinitionType $eBayMotorsProPaymentMethodCheckOutEnabled
	var $eBayMotorsProPaymentMethodCheckOutEnabled;
	// @var eBayMotorsProShippingMethodEnabledDefinitionType $eBayMotorsProShippingMethodEnabled
	var $eBayMotorsProShippingMethodEnabled;
	// @var eBayMotorsProCounterOfferEnabledDefinitionType $eBayMotorsProCounterOfferEnabled
	var $eBayMotorsProCounterOfferEnabled;
	// @var eBayMotorsProSellerContactDetailsEnabledDefinitionType $eBayMotorsProSellerContactDetailsEnabled
	var $eBayMotorsProSellerContactDetailsEnabled;
	// @var LocalMarketAdFormatEnabledDefinitionType $LocalMarketAdFormatEnabled
	var $LocalMarketAdFormatEnabled;
	// @var LocalMarketContactByPhoneEnabledDefinitionType $LocalMarketContactByPhoneEnabled
	var $LocalMarketContactByPhoneEnabled;
	// @var LocalMarketPhoneCountDefinitionType $LocalMarketPhoneCount
	var $LocalMarketPhoneCount;
	// @var LocalMarketContactByAddressEnabledDefinitionType $LocalMarketContactByAddressEnabled
	var $LocalMarketContactByAddressEnabled;
	// @var LocalMarketStreetCountDefinitionType $LocalMarketStreetCount
	var $LocalMarketStreetCount;
	// @var LocalMarketCompanyNameEnabledDefinitionType $LocalMarketCompanyNameEnabled
	var $LocalMarketCompanyNameEnabled;
	// @var LocalMarketContactByEmailEnabledDefinitionType $LocalMarketContactByEmailEnabled
	var $LocalMarketContactByEmailEnabled;
	// @var LocalMarketBestOfferEnabledDefinitionType $LocalMarketBestOfferEnabled
	var $LocalMarketBestOfferEnabled;
	// @var LocalMarketAutoAcceptEnabledDefinitionType $LocalMarketAutoAcceptEnabled
	var $LocalMarketAutoAcceptEnabled;
	// @var LocalMarketAutoDeclineEnabledDefinitionType $LocalMarketAutoDeclineEnabled
	var $LocalMarketAutoDeclineEnabled;
	// @var LocalMarketPaymentMethodCheckOutEnabledDefinitionType $LocalMarketPaymentMethodCheckOutEnabled
	var $LocalMarketPaymentMethodCheckOutEnabled;
	// @var LocalMarketShippingMethodEnabledDefinitionType $LocalMarketShippingMethodEnabled
	var $LocalMarketShippingMethodEnabled;
	// @var LocalMarketCounterOfferEnabledDefinitionType $LocalMarketCounterOfferEnabled
	var $LocalMarketCounterOfferEnabled;
	// @var LocalMarketSellerContactDetailsEnabledDefinitionType $LocalMarketSellerContactDetailsEnabled
	var $LocalMarketSellerContactDetailsEnabled;
	// @var ClassifiedAdPhoneCountDefinitionType $ClassifiedAdPhoneCount
	var $ClassifiedAdPhoneCount;
	// @var ClassifiedAdContactByAddressEnabledDefinitionType $ClassifiedAdContactByAddressEnabled
	var $ClassifiedAdContactByAddressEnabled;
	// @var ClassifiedAdStreetCountDefinitionType $ClassifiedAdStreetCount
	var $ClassifiedAdStreetCount;
	// @var ClassifiedAdCompanyNameEnabledDefinitionType $ClassifiedAdCompanyNameEnabled
	var $ClassifiedAdCompanyNameEnabled;
	// @var SpecialitySubscriptionDefinitionType $SpecialitySubscription
	var $SpecialitySubscription;
	// @var RegularSubscriptionDefinitionType $RegularSubscription
	var $RegularSubscription;
	// @var PremiumSubscriptionDefinitionType $PremiumSubscription
	var $PremiumSubscription;
	// @var NonSubscriptionDefinitionType $NonSubscription
	var $NonSubscription;
	// @var ReturnPolicyEnabledDefinitionType $ReturnPolicyEnabled
	var $ReturnPolicyEnabled;
	// @var HandlingTimeEnabledDefinitionType $HandlingTimeEnabled
	var $HandlingTimeEnabled;
	// @var PayPalRequiredForStoreOwnerDefinitionType $PayPalRequiredForStoreOwner
	var $PayPalRequiredForStoreOwner;
	// @var ReviseQuantityAllowedDefinitionType $ReviseQuantityAllowed
	var $ReviseQuantityAllowed;
	// @var RevisePriceAllowedDefinitionType $RevisePriceAllowed
	var $RevisePriceAllowed;
	// @var StoreOwnerExtendedListingDurationsEnabledDefinitionType $StoreOwnerExtendedListingDurationsEnabled
	var $StoreOwnerExtendedListingDurationsEnabled;
	// @var StoreOwnerExtendedListingDurationsDefinitionType $StoreOwnerExtendedListingDurations
	var $StoreOwnerExtendedListingDurations;
	// @var PaymentMethodDefinitionType $PaymentMethod
	var $PaymentMethod;
	// @var Group1MaxFlatShippingCostDefinitionType $Group1MaxFlatShippingCost
	var $Group1MaxFlatShippingCost;
	// @var Group2MaxFlatShippingCostDefinitionType $Group2MaxFlatShippingCost
	var $Group2MaxFlatShippingCost;
	// @var Group3MaxFlatShippingCostDefinitionType $Group3MaxFlatShippingCost
	var $Group3MaxFlatShippingCost;
	// @var MaxFlatShippingCostCBTExemptDefinitionType $MaxFlatShippingCostCBTExempt
	var $MaxFlatShippingCostCBTExempt;
	// @var MaxFlatShippingCostDefinitionType $MaxFlatShippingCost
	var $MaxFlatShippingCost;
	// @var VariationsEnabledDefinitionType $VariationsEnabled
	var $VariationsEnabled;
	// @var AttributeConversionEnabledFeatureDefinitionType $AttributeConversionEnabled
	var $AttributeConversionEnabled;
	// @var FreeGalleryPlusEnabledDefinitionType $FreeGalleryPlusEnabled
	var $FreeGalleryPlusEnabled;
	// @var FreePicturePackEnabledDefinitionType $FreePicturePackEnabled
	var $FreePicturePackEnabled;
	// end props

/**
 *

 * @return ListingDurationDefinitionsType
 */
	function getListingDurations()
	{
		return $this->ListingDurations;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setListingDurations($value)
	{
		$this->ListingDurations = $value;
	}
/**
 *

 * @return ShippingTermRequiredDefinitionType
 */
	function getShippingTermsRequired()
	{
		return $this->ShippingTermsRequired;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setShippingTermsRequired($value)
	{
		$this->ShippingTermsRequired = $value;
	}
/**
 *

 * @return BestOfferEnabledDefinitionType
 */
	function getBestOfferEnabled()
	{
		return $this->BestOfferEnabled;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setBestOfferEnabled($value)
	{
		$this->BestOfferEnabled = $value;
	}
/**
 *

 * @return DutchBINEnabledDefinitionType
 */
	function getDutchBINEnabled()
	{
		return $this->DutchBINEnabled;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setDutchBINEnabled($value)
	{
		$this->DutchBINEnabled = $value;
	}
/**
 *

 * @return UserConsentRequiredDefinitionType
 */
	function getUserConsentRequired()
	{
		return $this->UserConsentRequired;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setUserConsentRequired($value)
	{
		$this->UserConsentRequired = $value;
	}
/**
 *

 * @return HomePageFeaturedEnabledDefinitionType
 */
	function getHomePageFeaturedEnabled()
	{
		return $this->HomePageFeaturedEnabled;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setHomePageFeaturedEnabled($value)
	{
		$this->HomePageFeaturedEnabled = $value;
	}
/**
 *

 * @return ProPackEnabledDefinitionType
 */
	function getProPackEnabled()
	{
		return $this->ProPackEnabled;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setProPackEnabled($value)
	{
		$this->ProPackEnabled = $value;
	}
/**
 *

 * @return BasicUpgradePackEnabledDefinitionType
 */
	function getBasicUpgradePackEnabled()
	{
		return $this->BasicUpgradePackEnabled;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setBasicUpgradePackEnabled($value)
	{
		$this->BasicUpgradePackEnabled = $value;
	}
/**
 *

 * @return ValuePackEnabledDefinitionType
 */
	function getValuePackEnabled()
	{
		return $this->ValuePackEnabled;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setValuePackEnabled($value)
	{
		$this->ValuePackEnabled = $value;
	}
/**
 *

 * @return ProPackPlusEnabledDefinitionType
 */
	function getProPackPlusEnabled()
	{
		return $this->ProPackPlusEnabled;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setProPackPlusEnabled($value)
	{
		$this->ProPackPlusEnabled = $value;
	}
/**
 *

 * @return AdFormatEnabledDefinitionType
 */
	function getAdFormatEnabled()
	{
		return $this->AdFormatEnabled;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setAdFormatEnabled($value)
	{
		$this->AdFormatEnabled = $value;
	}
/**
 *

 * @return BestOfferCounterEnabledDefinitionType
 */
	function getBestOfferCounterEnabled()
	{
		return $this->BestOfferCounterEnabled;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setBestOfferCounterEnabled($value)
	{
		$this->BestOfferCounterEnabled = $value;
	}
/**
 *

 * @return BestOfferAutoDeclineEnabledDefinitionType
 */
	function getBestOfferAutoDeclineEnabled()
	{
		return $this->BestOfferAutoDeclineEnabled;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setBestOfferAutoDeclineEnabled($value)
	{
		$this->BestOfferAutoDeclineEnabled = $value;
	}
/**
 *

 * @return LocalMarketSpecialitySubscriptionDefinitionType
 */
	function getLocalMarketSpecialitySubscription()
	{
		return $this->LocalMarketSpecialitySubscription;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setLocalMarketSpecialitySubscription($value)
	{
		$this->LocalMarketSpecialitySubscription = $value;
	}
/**
 *

 * @return LocalMarketRegularSubscriptionDefinitionType
 */
	function getLocalMarketRegularSubscription()
	{
		return $this->LocalMarketRegularSubscription;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setLocalMarketRegularSubscription($value)
	{
		$this->LocalMarketRegularSubscription = $value;
	}
/**
 *

 * @return LocalMarketPremiumSubscriptionDefinitionType
 */
	function getLocalMarketPremiumSubscription()
	{
		return $this->LocalMarketPremiumSubscription;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setLocalMarketPremiumSubscription($value)
	{
		$this->LocalMarketPremiumSubscription = $value;
	}
/**
 *

 * @return LocalMarketNonSubscriptionDefinitionType
 */
	function getLocalMarketNonSubscription()
	{
		return $this->LocalMarketNonSubscription;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setLocalMarketNonSubscription($value)
	{
		$this->LocalMarketNonSubscription = $value;
	}
/**
 *

 * @return ExpressEnabledDefinitionType
 */
	function getExpressEnabled()
	{
		return $this->ExpressEnabled;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setExpressEnabled($value)
	{
		$this->ExpressEnabled = $value;
	}
/**
 *

 * @return ExpressPicturesRequiredDefinitionType
 */
	function getExpressPicturesRequired()
	{
		return $this->ExpressPicturesRequired;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setExpressPicturesRequired($value)
	{
		$this->ExpressPicturesRequired = $value;
	}
/**
 *

 * @return ExpressConditionRequiredDefinitionType
 */
	function getExpressConditionRequired()
	{
		return $this->ExpressConditionRequired;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setExpressConditionRequired($value)
	{
		$this->ExpressConditionRequired = $value;
	}
/**
 *

 * @return MinimumReservePriceDefinitionType
 */
	function getMinimumReservePrice()
	{
		return $this->MinimumReservePrice;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setMinimumReservePrice($value)
	{
		$this->MinimumReservePrice = $value;
	}
/**
 *

 * @return TCREnabledDefinitionType
 */
	function getTransactionConfirmationRequestEnabled()
	{
		return $this->TransactionConfirmationRequestEnabled;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setTransactionConfirmationRequestEnabled($value)
	{
		$this->TransactionConfirmationRequestEnabled = $value;
	}
/**
 *

 * @return SellerContactDetailsEnabledDefinitionType
 */
	function getSellerContactDetailsEnabled()
	{
		return $this->SellerContactDetailsEnabled;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setSellerContactDetailsEnabled($value)
	{
		$this->SellerContactDetailsEnabled = $value;
	}
/**
 *

 * @return StoreInventoryEnabledDefinitionType
 */
	function getStoreInventoryEnabled()
	{
		return $this->StoreInventoryEnabled;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setStoreInventoryEnabled($value)
	{
		$this->StoreInventoryEnabled = $value;
	}
/**
 *

 * @return SkypeMeTransactionalEnabledDefinitionType
 */
	function getSkypeMeTransactionalEnabled()
	{
		return $this->SkypeMeTransactionalEnabled;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setSkypeMeTransactionalEnabled($value)
	{
		$this->SkypeMeTransactionalEnabled = $value;
	}
/**
 *

 * @return SkypeMeNonTransactionalEnabledDefinitionType
 */
	function getSkypeMeNonTransactionalEnabled()
	{
		return $this->SkypeMeNonTransactionalEnabled;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setSkypeMeNonTransactionalEnabled($value)
	{
		$this->SkypeMeNonTransactionalEnabled = $value;
	}
/**
 *

 * @return LocalListingDistancesRegularDefinitionType
 */
	function getLocalListingDistancesRegular()
	{
		return $this->LocalListingDistancesRegular;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setLocalListingDistancesRegular($value)
	{
		$this->LocalListingDistancesRegular = $value;
	}
/**
 *

 * @return LocalListingDistancesSpecialtyDefinitionType
 */
	function getLocalListingDistancesSpecialty()
	{
		return $this->LocalListingDistancesSpecialty;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setLocalListingDistancesSpecialty($value)
	{
		$this->LocalListingDistancesSpecialty = $value;
	}
/**
 *

 * @return LocalListingDistancesNonSubscriptionDefinitionType
 */
	function getLocalListingDistancesNonSubscription()
	{
		return $this->LocalListingDistancesNonSubscription;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setLocalListingDistancesNonSubscription($value)
	{
		$this->LocalListingDistancesNonSubscription = $value;
	}
/**
 *

 * @return ClassifiedAdPaymentMethodEnabledDefinitionType
 */
	function getClassifiedAdPaymentMethodEnabled()
	{
		return $this->ClassifiedAdPaymentMethodEnabled;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setClassifiedAdPaymentMethodEnabled($value)
	{
		$this->ClassifiedAdPaymentMethodEnabled = $value;
	}
/**
 *

 * @return ClassifiedAdShippingMethodEnabledDefinitionType
 */
	function getClassifiedAdShippingMethodEnabled()
	{
		return $this->ClassifiedAdShippingMethodEnabled;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setClassifiedAdShippingMethodEnabled($value)
	{
		$this->ClassifiedAdShippingMethodEnabled = $value;
	}
/**
 *

 * @return ClassifiedAdBestOfferEnabledDefinitionType
 */
	function getClassifiedAdBestOfferEnabled()
	{
		return $this->ClassifiedAdBestOfferEnabled;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setClassifiedAdBestOfferEnabled($value)
	{
		$this->ClassifiedAdBestOfferEnabled = $value;
	}
/**
 *

 * @return ClassifiedAdCounterOfferEnabledDefinitionType
 */
	function getClassifiedAdCounterOfferEnabled()
	{
		return $this->ClassifiedAdCounterOfferEnabled;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setClassifiedAdCounterOfferEnabled($value)
	{
		$this->ClassifiedAdCounterOfferEnabled = $value;
	}
/**
 *

 * @return ClassifiedAdAutoDeclineEnabledDefinitionType
 */
	function getClassifiedAdAutoDeclineEnabled()
	{
		return $this->ClassifiedAdAutoDeclineEnabled;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setClassifiedAdAutoDeclineEnabled($value)
	{
		$this->ClassifiedAdAutoDeclineEnabled = $value;
	}
/**
 *

 * @return ClassifiedAdContactByPhoneEnabledDefinitionType
 */
	function getClassifiedAdContactByPhoneEnabled()
	{
		return $this->ClassifiedAdContactByPhoneEnabled;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setClassifiedAdContactByPhoneEnabled($value)
	{
		$this->ClassifiedAdContactByPhoneEnabled = $value;
	}
/**
 *

 * @return ClassifiedAdContactByEmailEnabledDefintionType
 */
	function getClassifiedAdContactByEmailEnabled()
	{
		return $this->ClassifiedAdContactByEmailEnabled;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setClassifiedAdContactByEmailEnabled($value)
	{
		$this->ClassifiedAdContactByEmailEnabled = $value;
	}
/**
 *

 * @return SafePaymentRequiredDefinitionType
 */
	function getSafePaymentRequired()
	{
		return $this->SafePaymentRequired;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setSafePaymentRequired($value)
	{
		$this->SafePaymentRequired = $value;
	}
/**
 *

 * @return ClassifiedAdPayPerLeadEnabledDefinitionType
 */
	function getClassifiedAdPayPerLeadEnabled()
	{
		return $this->ClassifiedAdPayPerLeadEnabled;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setClassifiedAdPayPerLeadEnabled($value)
	{
		$this->ClassifiedAdPayPerLeadEnabled = $value;
	}
/**
 *

 * @return ItemSpecificsEnabledDefinitionType
 */
	function getItemSpecificsEnabled()
	{
		return $this->ItemSpecificsEnabled;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setItemSpecificsEnabled($value)
	{
		$this->ItemSpecificsEnabled = $value;
	}
/**
 *

 * @return PaisaPayFullEscrowEnabledDefinitionType
 */
	function getPaisaPayFullEscrowEnabled()
	{
		return $this->PaisaPayFullEscrowEnabled;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setPaisaPayFullEscrowEnabled($value)
	{
		$this->PaisaPayFullEscrowEnabled = $value;
	}
/**
 *

 * @return BestOfferAutoAcceptEnabledDefinitionType
 */
	function getBestOfferAutoAcceptEnabled()
	{
		return $this->BestOfferAutoAcceptEnabled;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setBestOfferAutoAcceptEnabled($value)
	{
		$this->BestOfferAutoAcceptEnabled = $value;
	}
/**
 *

 * @return ClassifiedAdAutoAcceptEnabledDefinitionType
 */
	function getClassifiedAdAutoAcceptEnabled()
	{
		return $this->ClassifiedAdAutoAcceptEnabled;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setClassifiedAdAutoAcceptEnabled($value)
	{
		$this->ClassifiedAdAutoAcceptEnabled = $value;
	}
/**
 *

 * @return CrossBorderTradeNorthAmericaEnabledDefinitionType
 */
	function getCrossBorderTradeNorthAmericaEnabled()
	{
		return $this->CrossBorderTradeNorthAmericaEnabled;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setCrossBorderTradeNorthAmericaEnabled($value)
	{
		$this->CrossBorderTradeNorthAmericaEnabled = $value;
	}
/**
 *

 * @return CrossBorderTradeGBEnabledDefinitionType
 */
	function getCrossBorderTradeGBEnabled()
	{
		return $this->CrossBorderTradeGBEnabled;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setCrossBorderTradeGBEnabled($value)
	{
		$this->CrossBorderTradeGBEnabled = $value;
	}
/**
 *

 * @return CrossBorderTradeAustraliaEnabledDefinitionType
 */
	function getCrossBorderTradeAustraliaEnabled()
	{
		return $this->CrossBorderTradeAustraliaEnabled;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setCrossBorderTradeAustraliaEnabled($value)
	{
		$this->CrossBorderTradeAustraliaEnabled = $value;
	}
/**
 *

 * @return PayPalBuyerProtectionEnabledDefinitionType
 */
	function getPayPalBuyerProtectionEnabled()
	{
		return $this->PayPalBuyerProtectionEnabled;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setPayPalBuyerProtectionEnabled($value)
	{
		$this->PayPalBuyerProtectionEnabled = $value;
	}
/**
 *

 * @return BuyerGuaranteeEnabledDefinitionType
 */
	function getBuyerGuaranteeEnabled()
	{
		return $this->BuyerGuaranteeEnabled;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setBuyerGuaranteeEnabled($value)
	{
		$this->BuyerGuaranteeEnabled = $value;
	}
/**
 *

 * @return CombinedFixedPriceTreatmentEnabledDefinitionType
 */
	function getCombinedFixedPriceTreatmentEnabled()
	{
		return $this->CombinedFixedPriceTreatmentEnabled;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setCombinedFixedPriceTreatmentEnabled($value)
	{
		$this->CombinedFixedPriceTreatmentEnabled = $value;
	}
/**
 *

 * @return ListingEnhancementDurationDefinitionType
 */
	function getGalleryFeaturedDurations()
	{
		return $this->GalleryFeaturedDurations;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setGalleryFeaturedDurations($value)
	{
		$this->GalleryFeaturedDurations = $value;
	}
/**
 *

 * @return INEscrowWorkflowTimelineDefinitionType
 */
	function getINEscrowWorkflowTimeline()
	{
		return $this->INEscrowWorkflowTimeline;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setINEscrowWorkflowTimeline($value)
	{
		$this->INEscrowWorkflowTimeline = $value;
	}
/**
 *

 * @return PayPalRequiredDefinitionType
 */
	function getPayPalRequired()
	{
		return $this->PayPalRequired;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setPayPalRequired($value)
	{
		$this->PayPalRequired = $value;
	}
/**
 *

 * @return eBayMotorsProAdFormatEnabledDefinitionType
 */
	function getEBayMotorsProAdFormatEnabled()
	{
		return $this->eBayMotorsProAdFormatEnabled;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setEBayMotorsProAdFormatEnabled($value)
	{
		$this->eBayMotorsProAdFormatEnabled = $value;
	}
/**
 *

 * @return eBayMotorsProContactByPhoneEnabledDefinitionType
 */
	function getEBayMotorsProContactByPhoneEnabled()
	{
		return $this->eBayMotorsProContactByPhoneEnabled;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setEBayMotorsProContactByPhoneEnabled($value)
	{
		$this->eBayMotorsProContactByPhoneEnabled = $value;
	}
/**
 *

 * @return eBayMotorsProPhoneCountDefinitionType
 */
	function getEBayMotorsProPhoneCount()
	{
		return $this->eBayMotorsProPhoneCount;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setEBayMotorsProPhoneCount($value)
	{
		$this->eBayMotorsProPhoneCount = $value;
	}
/**
 *

 * @return eBayMotorsProContactByAddressEnabledDefinitionType
 */
	function getEBayMotorsProContactByAddressEnabled()
	{
		return $this->eBayMotorsProContactByAddressEnabled;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setEBayMotorsProContactByAddressEnabled($value)
	{
		$this->eBayMotorsProContactByAddressEnabled = $value;
	}
/**
 *

 * @return eBayMotorsProStreetCountDefinitionType
 */
	function getEBayMotorsProStreetCount()
	{
		return $this->eBayMotorsProStreetCount;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setEBayMotorsProStreetCount($value)
	{
		$this->eBayMotorsProStreetCount = $value;
	}
/**
 *

 * @return eBayMotorsProCompanyNameEnabledDefinitionType
 */
	function getEBayMotorsProCompanyNameEnabled()
	{
		return $this->eBayMotorsProCompanyNameEnabled;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setEBayMotorsProCompanyNameEnabled($value)
	{
		$this->eBayMotorsProCompanyNameEnabled = $value;
	}
/**
 *

 * @return eBayMotorsProContactByEmailEnabledDefinitionType
 */
	function getEBayMotorsProContactByEmailEnabled()
	{
		return $this->eBayMotorsProContactByEmailEnabled;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setEBayMotorsProContactByEmailEnabled($value)
	{
		$this->eBayMotorsProContactByEmailEnabled = $value;
	}
/**
 *

 * @return eBayMotorsProBestOfferEnabledDefinitionType
 */
	function getEBayMotorsProBestOfferEnabled()
	{
		return $this->eBayMotorsProBestOfferEnabled;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setEBayMotorsProBestOfferEnabled($value)
	{
		$this->eBayMotorsProBestOfferEnabled = $value;
	}
/**
 *

 * @return eBayMotorsProAutoAcceptEnabledDefinitionType
 */
	function getEBayMotorsProAutoAcceptEnabled()
	{
		return $this->eBayMotorsProAutoAcceptEnabled;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setEBayMotorsProAutoAcceptEnabled($value)
	{
		$this->eBayMotorsProAutoAcceptEnabled = $value;
	}
/**
 *

 * @return eBayMotorsProAutoDeclineEnabledDefinitionType
 */
	function getEBayMotorsProAutoDeclineEnabled()
	{
		return $this->eBayMotorsProAutoDeclineEnabled;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setEBayMotorsProAutoDeclineEnabled($value)
	{
		$this->eBayMotorsProAutoDeclineEnabled = $value;
	}
/**
 *

 * @return eBayMotorsProPaymentMethodCheckOutEnabledDefinitionType
 */
	function getEBayMotorsProPaymentMethodCheckOutEnabled()
	{
		return $this->eBayMotorsProPaymentMethodCheckOutEnabled;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setEBayMotorsProPaymentMethodCheckOutEnabled($value)
	{
		$this->eBayMotorsProPaymentMethodCheckOutEnabled = $value;
	}
/**
 *

 * @return eBayMotorsProShippingMethodEnabledDefinitionType
 */
	function getEBayMotorsProShippingMethodEnabled()
	{
		return $this->eBayMotorsProShippingMethodEnabled;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setEBayMotorsProShippingMethodEnabled($value)
	{
		$this->eBayMotorsProShippingMethodEnabled = $value;
	}
/**
 *

 * @return eBayMotorsProCounterOfferEnabledDefinitionType
 */
	function getEBayMotorsProCounterOfferEnabled()
	{
		return $this->eBayMotorsProCounterOfferEnabled;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setEBayMotorsProCounterOfferEnabled($value)
	{
		$this->eBayMotorsProCounterOfferEnabled = $value;
	}
/**
 *

 * @return eBayMotorsProSellerContactDetailsEnabledDefinitionType
 */
	function getEBayMotorsProSellerContactDetailsEnabled()
	{
		return $this->eBayMotorsProSellerContactDetailsEnabled;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setEBayMotorsProSellerContactDetailsEnabled($value)
	{
		$this->eBayMotorsProSellerContactDetailsEnabled = $value;
	}
/**
 *

 * @return LocalMarketAdFormatEnabledDefinitionType
 */
	function getLocalMarketAdFormatEnabled()
	{
		return $this->LocalMarketAdFormatEnabled;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setLocalMarketAdFormatEnabled($value)
	{
		$this->LocalMarketAdFormatEnabled = $value;
	}
/**
 *

 * @return LocalMarketContactByPhoneEnabledDefinitionType
 */
	function getLocalMarketContactByPhoneEnabled()
	{
		return $this->LocalMarketContactByPhoneEnabled;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setLocalMarketContactByPhoneEnabled($value)
	{
		$this->LocalMarketContactByPhoneEnabled = $value;
	}
/**
 *

 * @return LocalMarketPhoneCountDefinitionType
 */
	function getLocalMarketPhoneCount()
	{
		return $this->LocalMarketPhoneCount;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setLocalMarketPhoneCount($value)
	{
		$this->LocalMarketPhoneCount = $value;
	}
/**
 *

 * @return LocalMarketContactByAddressEnabledDefinitionType
 */
	function getLocalMarketContactByAddressEnabled()
	{
		return $this->LocalMarketContactByAddressEnabled;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setLocalMarketContactByAddressEnabled($value)
	{
		$this->LocalMarketContactByAddressEnabled = $value;
	}
/**
 *

 * @return LocalMarketStreetCountDefinitionType
 */
	function getLocalMarketStreetCount()
	{
		return $this->LocalMarketStreetCount;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setLocalMarketStreetCount($value)
	{
		$this->LocalMarketStreetCount = $value;
	}
/**
 *

 * @return LocalMarketCompanyNameEnabledDefinitionType
 */
	function getLocalMarketCompanyNameEnabled()
	{
		return $this->LocalMarketCompanyNameEnabled;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setLocalMarketCompanyNameEnabled($value)
	{
		$this->LocalMarketCompanyNameEnabled = $value;
	}
/**
 *

 * @return LocalMarketContactByEmailEnabledDefinitionType
 */
	function getLocalMarketContactByEmailEnabled()
	{
		return $this->LocalMarketContactByEmailEnabled;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setLocalMarketContactByEmailEnabled($value)
	{
		$this->LocalMarketContactByEmailEnabled = $value;
	}
/**
 *

 * @return LocalMarketBestOfferEnabledDefinitionType
 */
	function getLocalMarketBestOfferEnabled()
	{
		return $this->LocalMarketBestOfferEnabled;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setLocalMarketBestOfferEnabled($value)
	{
		$this->LocalMarketBestOfferEnabled = $value;
	}
/**
 *

 * @return LocalMarketAutoAcceptEnabledDefinitionType
 */
	function getLocalMarketAutoAcceptEnabled()
	{
		return $this->LocalMarketAutoAcceptEnabled;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setLocalMarketAutoAcceptEnabled($value)
	{
		$this->LocalMarketAutoAcceptEnabled = $value;
	}
/**
 *

 * @return LocalMarketAutoDeclineEnabledDefinitionType
 */
	function getLocalMarketAutoDeclineEnabled()
	{
		return $this->LocalMarketAutoDeclineEnabled;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setLocalMarketAutoDeclineEnabled($value)
	{
		$this->LocalMarketAutoDeclineEnabled = $value;
	}
/**
 *

 * @return LocalMarketPaymentMethodCheckOutEnabledDefinitionType
 */
	function getLocalMarketPaymentMethodCheckOutEnabled()
	{
		return $this->LocalMarketPaymentMethodCheckOutEnabled;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setLocalMarketPaymentMethodCheckOutEnabled($value)
	{
		$this->LocalMarketPaymentMethodCheckOutEnabled = $value;
	}
/**
 *

 * @return LocalMarketShippingMethodEnabledDefinitionType
 */
	function getLocalMarketShippingMethodEnabled()
	{
		return $this->LocalMarketShippingMethodEnabled;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setLocalMarketShippingMethodEnabled($value)
	{
		$this->LocalMarketShippingMethodEnabled = $value;
	}
/**
 *

 * @return LocalMarketCounterOfferEnabledDefinitionType
 */
	function getLocalMarketCounterOfferEnabled()
	{
		return $this->LocalMarketCounterOfferEnabled;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setLocalMarketCounterOfferEnabled($value)
	{
		$this->LocalMarketCounterOfferEnabled = $value;
	}
/**
 *

 * @return LocalMarketSellerContactDetailsEnabledDefinitionType
 */
	function getLocalMarketSellerContactDetailsEnabled()
	{
		return $this->LocalMarketSellerContactDetailsEnabled;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setLocalMarketSellerContactDetailsEnabled($value)
	{
		$this->LocalMarketSellerContactDetailsEnabled = $value;
	}
/**
 *

 * @return ClassifiedAdPhoneCountDefinitionType
 */
	function getClassifiedAdPhoneCount()
	{
		return $this->ClassifiedAdPhoneCount;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setClassifiedAdPhoneCount($value)
	{
		$this->ClassifiedAdPhoneCount = $value;
	}
/**
 *

 * @return ClassifiedAdContactByAddressEnabledDefinitionType
 */
	function getClassifiedAdContactByAddressEnabled()
	{
		return $this->ClassifiedAdContactByAddressEnabled;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setClassifiedAdContactByAddressEnabled($value)
	{
		$this->ClassifiedAdContactByAddressEnabled = $value;
	}
/**
 *

 * @return ClassifiedAdStreetCountDefinitionType
 */
	function getClassifiedAdStreetCount()
	{
		return $this->ClassifiedAdStreetCount;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setClassifiedAdStreetCount($value)
	{
		$this->ClassifiedAdStreetCount = $value;
	}
/**
 *

 * @return ClassifiedAdCompanyNameEnabledDefinitionType
 */
	function getClassifiedAdCompanyNameEnabled()
	{
		return $this->ClassifiedAdCompanyNameEnabled;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setClassifiedAdCompanyNameEnabled($value)
	{
		$this->ClassifiedAdCompanyNameEnabled = $value;
	}
/**
 *

 * @return SpecialitySubscriptionDefinitionType
 */
	function getSpecialitySubscription()
	{
		return $this->SpecialitySubscription;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setSpecialitySubscription($value)
	{
		$this->SpecialitySubscription = $value;
	}
/**
 *

 * @return RegularSubscriptionDefinitionType
 */
	function getRegularSubscription()
	{
		return $this->RegularSubscription;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setRegularSubscription($value)
	{
		$this->RegularSubscription = $value;
	}
/**
 *

 * @return PremiumSubscriptionDefinitionType
 */
	function getPremiumSubscription()
	{
		return $this->PremiumSubscription;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setPremiumSubscription($value)
	{
		$this->PremiumSubscription = $value;
	}
/**
 *

 * @return NonSubscriptionDefinitionType
 */
	function getNonSubscription()
	{
		return $this->NonSubscription;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setNonSubscription($value)
	{
		$this->NonSubscription = $value;
	}
/**
 *

 * @return ReturnPolicyEnabledDefinitionType
 */
	function getReturnPolicyEnabled()
	{
		return $this->ReturnPolicyEnabled;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setReturnPolicyEnabled($value)
	{
		$this->ReturnPolicyEnabled = $value;
	}
/**
 *

 * @return HandlingTimeEnabledDefinitionType
 */
	function getHandlingTimeEnabled()
	{
		return $this->HandlingTimeEnabled;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setHandlingTimeEnabled($value)
	{
		$this->HandlingTimeEnabled = $value;
	}
/**
 *

 * @return PayPalRequiredForStoreOwnerDefinitionType
 */
	function getPayPalRequiredForStoreOwner()
	{
		return $this->PayPalRequiredForStoreOwner;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setPayPalRequiredForStoreOwner($value)
	{
		$this->PayPalRequiredForStoreOwner = $value;
	}
/**
 *

 * @return ReviseQuantityAllowedDefinitionType
 */
	function getReviseQuantityAllowed()
	{
		return $this->ReviseQuantityAllowed;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setReviseQuantityAllowed($value)
	{
		$this->ReviseQuantityAllowed = $value;
	}
/**
 *

 * @return RevisePriceAllowedDefinitionType
 */
	function getRevisePriceAllowed()
	{
		return $this->RevisePriceAllowed;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setRevisePriceAllowed($value)
	{
		$this->RevisePriceAllowed = $value;
	}
/**
 *

 * @return StoreOwnerExtendedListingDurationsEnabledDefinitionType
 */
	function getStoreOwnerExtendedListingDurationsEnabled()
	{
		return $this->StoreOwnerExtendedListingDurationsEnabled;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setStoreOwnerExtendedListingDurationsEnabled($value)
	{
		$this->StoreOwnerExtendedListingDurationsEnabled = $value;
	}
/**
 *

 * @return StoreOwnerExtendedListingDurationsDefinitionType
 */
	function getStoreOwnerExtendedListingDurations()
	{
		return $this->StoreOwnerExtendedListingDurations;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setStoreOwnerExtendedListingDurations($value)
	{
		$this->StoreOwnerExtendedListingDurations = $value;
	}
/**
 *

 * @return PaymentMethodDefinitionType
 */
	function getPaymentMethod()
	{
		return $this->PaymentMethod;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setPaymentMethod($value)
	{
		$this->PaymentMethod = $value;
	}
/**
 *

 * @return Group1MaxFlatShippingCostDefinitionType
 */
	function getGroup1MaxFlatShippingCost()
	{
		return $this->Group1MaxFlatShippingCost;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setGroup1MaxFlatShippingCost($value)
	{
		$this->Group1MaxFlatShippingCost = $value;
	}
/**
 *

 * @return Group2MaxFlatShippingCostDefinitionType
 */
	function getGroup2MaxFlatShippingCost()
	{
		return $this->Group2MaxFlatShippingCost;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setGroup2MaxFlatShippingCost($value)
	{
		$this->Group2MaxFlatShippingCost = $value;
	}
/**
 *

 * @return Group3MaxFlatShippingCostDefinitionType
 */
	function getGroup3MaxFlatShippingCost()
	{
		return $this->Group3MaxFlatShippingCost;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setGroup3MaxFlatShippingCost($value)
	{
		$this->Group3MaxFlatShippingCost = $value;
	}
/**
 *

 * @return MaxFlatShippingCostCBTExemptDefinitionType
 */
	function getMaxFlatShippingCostCBTExempt()
	{
		return $this->MaxFlatShippingCostCBTExempt;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setMaxFlatShippingCostCBTExempt($value)
	{
		$this->MaxFlatShippingCostCBTExempt = $value;
	}
/**
 *

 * @return MaxFlatShippingCostDefinitionType
 */
	function getMaxFlatShippingCost()
	{
		return $this->MaxFlatShippingCost;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setMaxFlatShippingCost($value)
	{
		$this->MaxFlatShippingCost = $value;
	}
/**
 *

 * @return VariationsEnabledDefinitionType
 */
	function getVariationsEnabled()
	{
		return $this->VariationsEnabled;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setVariationsEnabled($value)
	{
		$this->VariationsEnabled = $value;
	}
/**
 *

 * @return AttributeConversionEnabledFeatureDefinitionType
 */
	function getAttributeConversionEnabled()
	{
		return $this->AttributeConversionEnabled;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setAttributeConversionEnabled($value)
	{
		$this->AttributeConversionEnabled = $value;
	}
/**
 *

 * @return FreeGalleryPlusEnabledDefinitionType
 */
	function getFreeGalleryPlusEnabled()
	{
		return $this->FreeGalleryPlusEnabled;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setFreeGalleryPlusEnabled($value)
	{
		$this->FreeGalleryPlusEnabled = $value;
	}
/**
 *

 * @return FreePicturePackEnabledDefinitionType
 */
	function getFreePicturePackEnabled()
	{
		return $this->FreePicturePackEnabled;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setFreePicturePackEnabled($value)
	{
		$this->FreePicturePackEnabled = $value;
	}
/**
 *

 * @return 
 */
	function FeatureDefinitionsType()
	{
		$this->EbatNs_ComplexType('FeatureDefinitionsType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'ListingDurations' =>
				array(
					'required' => false,
					'type' => 'ListingDurationDefinitionsType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'ShippingTermsRequired' =>
				array(
					'required' => false,
					'type' => 'ShippingTermRequiredDefinitionType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'BestOfferEnabled' =>
				array(
					'required' => false,
					'type' => 'BestOfferEnabledDefinitionType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'DutchBINEnabled' =>
				array(
					'required' => false,
					'type' => 'DutchBINEnabledDefinitionType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'UserConsentRequired' =>
				array(
					'required' => false,
					'type' => 'UserConsentRequiredDefinitionType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'HomePageFeaturedEnabled' =>
				array(
					'required' => false,
					'type' => 'HomePageFeaturedEnabledDefinitionType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'ProPackEnabled' =>
				array(
					'required' => false,
					'type' => 'ProPackEnabledDefinitionType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'BasicUpgradePackEnabled' =>
				array(
					'required' => false,
					'type' => 'BasicUpgradePackEnabledDefinitionType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'ValuePackEnabled' =>
				array(
					'required' => false,
					'type' => 'ValuePackEnabledDefinitionType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'ProPackPlusEnabled' =>
				array(
					'required' => false,
					'type' => 'ProPackPlusEnabledDefinitionType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'AdFormatEnabled' =>
				array(
					'required' => false,
					'type' => 'AdFormatEnabledDefinitionType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'BestOfferCounterEnabled' =>
				array(
					'required' => false,
					'type' => 'BestOfferCounterEnabledDefinitionType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'BestOfferAutoDeclineEnabled' =>
				array(
					'required' => false,
					'type' => 'BestOfferAutoDeclineEnabledDefinitionType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'LocalMarketSpecialitySubscription' =>
				array(
					'required' => false,
					'type' => 'LocalMarketSpecialitySubscriptionDefinitionType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'LocalMarketRegularSubscription' =>
				array(
					'required' => false,
					'type' => 'LocalMarketRegularSubscriptionDefinitionType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'LocalMarketPremiumSubscription' =>
				array(
					'required' => false,
					'type' => 'LocalMarketPremiumSubscriptionDefinitionType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'LocalMarketNonSubscription' =>
				array(
					'required' => false,
					'type' => 'LocalMarketNonSubscriptionDefinitionType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'ExpressEnabled' =>
				array(
					'required' => false,
					'type' => 'ExpressEnabledDefinitionType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'ExpressPicturesRequired' =>
				array(
					'required' => false,
					'type' => 'ExpressPicturesRequiredDefinitionType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'ExpressConditionRequired' =>
				array(
					'required' => false,
					'type' => 'ExpressConditionRequiredDefinitionType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'MinimumReservePrice' =>
				array(
					'required' => false,
					'type' => 'MinimumReservePriceDefinitionType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'TransactionConfirmationRequestEnabled' =>
				array(
					'required' => false,
					'type' => 'TCREnabledDefinitionType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'SellerContactDetailsEnabled' =>
				array(
					'required' => false,
					'type' => 'SellerContactDetailsEnabledDefinitionType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'StoreInventoryEnabled' =>
				array(
					'required' => false,
					'type' => 'StoreInventoryEnabledDefinitionType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'SkypeMeTransactionalEnabled' =>
				array(
					'required' => false,
					'type' => 'SkypeMeTransactionalEnabledDefinitionType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'SkypeMeNonTransactionalEnabled' =>
				array(
					'required' => false,
					'type' => 'SkypeMeNonTransactionalEnabledDefinitionType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'LocalListingDistancesRegular' =>
				array(
					'required' => false,
					'type' => 'LocalListingDistancesRegularDefinitionType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'LocalListingDistancesSpecialty' =>
				array(
					'required' => false,
					'type' => 'LocalListingDistancesSpecialtyDefinitionType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'LocalListingDistancesNonSubscription' =>
				array(
					'required' => false,
					'type' => 'LocalListingDistancesNonSubscriptionDefinitionType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'ClassifiedAdPaymentMethodEnabled' =>
				array(
					'required' => false,
					'type' => 'ClassifiedAdPaymentMethodEnabledDefinitionType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'ClassifiedAdShippingMethodEnabled' =>
				array(
					'required' => false,
					'type' => 'ClassifiedAdShippingMethodEnabledDefinitionType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'ClassifiedAdBestOfferEnabled' =>
				array(
					'required' => false,
					'type' => 'ClassifiedAdBestOfferEnabledDefinitionType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'ClassifiedAdCounterOfferEnabled' =>
				array(
					'required' => false,
					'type' => 'ClassifiedAdCounterOfferEnabledDefinitionType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'ClassifiedAdAutoDeclineEnabled' =>
				array(
					'required' => false,
					'type' => 'ClassifiedAdAutoDeclineEnabledDefinitionType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'ClassifiedAdContactByPhoneEnabled' =>
				array(
					'required' => false,
					'type' => 'ClassifiedAdContactByPhoneEnabledDefinitionType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'ClassifiedAdContactByEmailEnabled' =>
				array(
					'required' => false,
					'type' => 'ClassifiedAdContactByEmailEnabledDefintionType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'SafePaymentRequired' =>
				array(
					'required' => false,
					'type' => 'SafePaymentRequiredDefinitionType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'ClassifiedAdPayPerLeadEnabled' =>
				array(
					'required' => false,
					'type' => 'ClassifiedAdPayPerLeadEnabledDefinitionType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'ItemSpecificsEnabled' =>
				array(
					'required' => false,
					'type' => 'ItemSpecificsEnabledDefinitionType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'PaisaPayFullEscrowEnabled' =>
				array(
					'required' => false,
					'type' => 'PaisaPayFullEscrowEnabledDefinitionType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'BestOfferAutoAcceptEnabled' =>
				array(
					'required' => false,
					'type' => 'BestOfferAutoAcceptEnabledDefinitionType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'ClassifiedAdAutoAcceptEnabled' =>
				array(
					'required' => false,
					'type' => 'ClassifiedAdAutoAcceptEnabledDefinitionType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'CrossBorderTradeNorthAmericaEnabled' =>
				array(
					'required' => false,
					'type' => 'CrossBorderTradeNorthAmericaEnabledDefinitionType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'CrossBorderTradeGBEnabled' =>
				array(
					'required' => false,
					'type' => 'CrossBorderTradeGBEnabledDefinitionType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'CrossBorderTradeAustraliaEnabled' =>
				array(
					'required' => false,
					'type' => 'CrossBorderTradeAustraliaEnabledDefinitionType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'PayPalBuyerProtectionEnabled' =>
				array(
					'required' => false,
					'type' => 'PayPalBuyerProtectionEnabledDefinitionType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'BuyerGuaranteeEnabled' =>
				array(
					'required' => false,
					'type' => 'BuyerGuaranteeEnabledDefinitionType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'CombinedFixedPriceTreatmentEnabled' =>
				array(
					'required' => false,
					'type' => 'CombinedFixedPriceTreatmentEnabledDefinitionType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'GalleryFeaturedDurations' =>
				array(
					'required' => false,
					'type' => 'ListingEnhancementDurationDefinitionType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'INEscrowWorkflowTimeline' =>
				array(
					'required' => false,
					'type' => 'INEscrowWorkflowTimelineDefinitionType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'PayPalRequired' =>
				array(
					'required' => false,
					'type' => 'PayPalRequiredDefinitionType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'eBayMotorsProAdFormatEnabled' =>
				array(
					'required' => false,
					'type' => 'eBayMotorsProAdFormatEnabledDefinitionType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'eBayMotorsProContactByPhoneEnabled' =>
				array(
					'required' => false,
					'type' => 'eBayMotorsProContactByPhoneEnabledDefinitionType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'eBayMotorsProPhoneCount' =>
				array(
					'required' => false,
					'type' => 'eBayMotorsProPhoneCountDefinitionType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'eBayMotorsProContactByAddressEnabled' =>
				array(
					'required' => false,
					'type' => 'eBayMotorsProContactByAddressEnabledDefinitionType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'eBayMotorsProStreetCount' =>
				array(
					'required' => false,
					'type' => 'eBayMotorsProStreetCountDefinitionType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'eBayMotorsProCompanyNameEnabled' =>
				array(
					'required' => false,
					'type' => 'eBayMotorsProCompanyNameEnabledDefinitionType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'eBayMotorsProContactByEmailEnabled' =>
				array(
					'required' => false,
					'type' => 'eBayMotorsProContactByEmailEnabledDefinitionType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'eBayMotorsProBestOfferEnabled' =>
				array(
					'required' => false,
					'type' => 'eBayMotorsProBestOfferEnabledDefinitionType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'eBayMotorsProAutoAcceptEnabled' =>
				array(
					'required' => false,
					'type' => 'eBayMotorsProAutoAcceptEnabledDefinitionType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'eBayMotorsProAutoDeclineEnabled' =>
				array(
					'required' => false,
					'type' => 'eBayMotorsProAutoDeclineEnabledDefinitionType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'eBayMotorsProPaymentMethodCheckOutEnabled' =>
				array(
					'required' => false,
					'type' => 'eBayMotorsProPaymentMethodCheckOutEnabledDefinitionType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'eBayMotorsProShippingMethodEnabled' =>
				array(
					'required' => false,
					'type' => 'eBayMotorsProShippingMethodEnabledDefinitionType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'eBayMotorsProCounterOfferEnabled' =>
				array(
					'required' => false,
					'type' => 'eBayMotorsProCounterOfferEnabledDefinitionType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'eBayMotorsProSellerContactDetailsEnabled' =>
				array(
					'required' => false,
					'type' => 'eBayMotorsProSellerContactDetailsEnabledDefinitionType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'LocalMarketAdFormatEnabled' =>
				array(
					'required' => false,
					'type' => 'LocalMarketAdFormatEnabledDefinitionType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'LocalMarketContactByPhoneEnabled' =>
				array(
					'required' => false,
					'type' => 'LocalMarketContactByPhoneEnabledDefinitionType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'LocalMarketPhoneCount' =>
				array(
					'required' => false,
					'type' => 'LocalMarketPhoneCountDefinitionType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'LocalMarketContactByAddressEnabled' =>
				array(
					'required' => false,
					'type' => 'LocalMarketContactByAddressEnabledDefinitionType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'LocalMarketStreetCount' =>
				array(
					'required' => false,
					'type' => 'LocalMarketStreetCountDefinitionType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'LocalMarketCompanyNameEnabled' =>
				array(
					'required' => false,
					'type' => 'LocalMarketCompanyNameEnabledDefinitionType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'LocalMarketContactByEmailEnabled' =>
				array(
					'required' => false,
					'type' => 'LocalMarketContactByEmailEnabledDefinitionType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'LocalMarketBestOfferEnabled' =>
				array(
					'required' => false,
					'type' => 'LocalMarketBestOfferEnabledDefinitionType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'LocalMarketAutoAcceptEnabled' =>
				array(
					'required' => false,
					'type' => 'LocalMarketAutoAcceptEnabledDefinitionType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'LocalMarketAutoDeclineEnabled' =>
				array(
					'required' => false,
					'type' => 'LocalMarketAutoDeclineEnabledDefinitionType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'LocalMarketPaymentMethodCheckOutEnabled' =>
				array(
					'required' => false,
					'type' => 'LocalMarketPaymentMethodCheckOutEnabledDefinitionType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'LocalMarketShippingMethodEnabled' =>
				array(
					'required' => false,
					'type' => 'LocalMarketShippingMethodEnabledDefinitionType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'LocalMarketCounterOfferEnabled' =>
				array(
					'required' => false,
					'type' => 'LocalMarketCounterOfferEnabledDefinitionType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'LocalMarketSellerContactDetailsEnabled' =>
				array(
					'required' => false,
					'type' => 'LocalMarketSellerContactDetailsEnabledDefinitionType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'ClassifiedAdPhoneCount' =>
				array(
					'required' => false,
					'type' => 'ClassifiedAdPhoneCountDefinitionType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'ClassifiedAdContactByAddressEnabled' =>
				array(
					'required' => false,
					'type' => 'ClassifiedAdContactByAddressEnabledDefinitionType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'ClassifiedAdStreetCount' =>
				array(
					'required' => false,
					'type' => 'ClassifiedAdStreetCountDefinitionType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'ClassifiedAdCompanyNameEnabled' =>
				array(
					'required' => false,
					'type' => 'ClassifiedAdCompanyNameEnabledDefinitionType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'SpecialitySubscription' =>
				array(
					'required' => false,
					'type' => 'SpecialitySubscriptionDefinitionType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'RegularSubscription' =>
				array(
					'required' => false,
					'type' => 'RegularSubscriptionDefinitionType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'PremiumSubscription' =>
				array(
					'required' => false,
					'type' => 'PremiumSubscriptionDefinitionType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'NonSubscription' =>
				array(
					'required' => false,
					'type' => 'NonSubscriptionDefinitionType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'ReturnPolicyEnabled' =>
				array(
					'required' => false,
					'type' => 'ReturnPolicyEnabledDefinitionType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'HandlingTimeEnabled' =>
				array(
					'required' => false,
					'type' => 'HandlingTimeEnabledDefinitionType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'PayPalRequiredForStoreOwner' =>
				array(
					'required' => false,
					'type' => 'PayPalRequiredForStoreOwnerDefinitionType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'ReviseQuantityAllowed' =>
				array(
					'required' => false,
					'type' => 'ReviseQuantityAllowedDefinitionType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'RevisePriceAllowed' =>
				array(
					'required' => false,
					'type' => 'RevisePriceAllowedDefinitionType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'StoreOwnerExtendedListingDurationsEnabled' =>
				array(
					'required' => false,
					'type' => 'StoreOwnerExtendedListingDurationsEnabledDefinitionType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'StoreOwnerExtendedListingDurations' =>
				array(
					'required' => false,
					'type' => 'StoreOwnerExtendedListingDurationsDefinitionType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'PaymentMethod' =>
				array(
					'required' => false,
					'type' => 'PaymentMethodDefinitionType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'Group1MaxFlatShippingCost' =>
				array(
					'required' => false,
					'type' => 'Group1MaxFlatShippingCostDefinitionType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'Group2MaxFlatShippingCost' =>
				array(
					'required' => false,
					'type' => 'Group2MaxFlatShippingCostDefinitionType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'Group3MaxFlatShippingCost' =>
				array(
					'required' => false,
					'type' => 'Group3MaxFlatShippingCostDefinitionType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'MaxFlatShippingCostCBTExempt' =>
				array(
					'required' => false,
					'type' => 'MaxFlatShippingCostCBTExemptDefinitionType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'MaxFlatShippingCost' =>
				array(
					'required' => false,
					'type' => 'MaxFlatShippingCostDefinitionType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'VariationsEnabled' =>
				array(
					'required' => false,
					'type' => 'VariationsEnabledDefinitionType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'AttributeConversionEnabled' =>
				array(
					'required' => false,
					'type' => 'AttributeConversionEnabledFeatureDefinitionType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'FreeGalleryPlusEnabled' =>
				array(
					'required' => false,
					'type' => 'FreeGalleryPlusEnabledDefinitionType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'FreePicturePackEnabled' =>
				array(
					'required' => false,
					'type' => 'FreePicturePackEnabledDefinitionType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				)
			));

	}
}
?>
