<?php
// autogenerated file 29.05.2009 15:17
// $Id: $
// $Log: $
//
//
require_once 'EbatNs_FacetType.php';

class FeedbackSummaryPeriodCodeType extends EbatNs_FacetType
{
	// start props
	// @var string $ThirtyDays
	var $ThirtyDays = 'ThirtyDays';
	// @var string $FiftyTwoWeeks
	var $FiftyTwoWeeks = 'FiftyTwoWeeks';
	// @var string $CustomCode
	var $CustomCode = 'CustomCode';
	// end props

/**
 *

 * @return 
 */
	function FeedbackSummaryPeriodCodeType()
	{
		$this->EbatNs_FacetType('FeedbackSummaryPeriodCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_FeedbackSummaryPeriodCodeType = new FeedbackSummaryPeriodCodeType();

?>
