<?php
// autogenerated file 29.05.2009 15:17
// $Id: $
// $Log: $
//
//
require_once 'EbatNs_ComplexType.php';

class FeedbackCommentArrayType extends EbatNs_ComplexType
{
	// start props
	// @var string $StoredCommentText
	var $StoredCommentText;
	// end props

/**
 *

 * @return string
 * @param  $index 
 */
	function getStoredCommentText($index = null)
	{
		if ($index) {
		return $this->StoredCommentText[$index];
	} else {
		return $this->StoredCommentText;
	}

	}
/**
 *

 * @return void
 * @param  $value 
 * @param  $index 
 */
	function setStoredCommentText($value, $index = null)
	{
		if ($index) {
	$this->StoredCommentText[$index] = $value;
	} else {
	$this->StoredCommentText = $value;
	}

	}
/**
 *

 * @return 
 */
	function FeedbackCommentArrayType()
	{
		$this->EbatNs_ComplexType('FeedbackCommentArrayType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'StoredCommentText' =>
				array(
					'required' => false,
					'type' => 'string',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => true,
					'cardinality' => '0..*'
				)
			));

	}
}
?>
