<?php
// autogenerated file 29.05.2009 15:17
// $Id: $
// $Log: $
//
//
require_once 'EbatNs_ComplexType.php';

class FeedbackRequirementsType extends EbatNs_ComplexType
{
	// start props
	// end props

/**
 *

 * @return 
 */
	function FeedbackRequirementsType()
	{
		$this->EbatNs_ComplexType('FeedbackRequirementsType', 'http://www.w3.org/2001/XMLSchema');
	$this->_attributes = array_merge($this->_attributes,
		array(
			'minimum' =>
			array(
				'name' => 'minimum',
				'type' => 'string',
				'use' => 'required'
			)
		));

	}
}
?>
