<?php
// autogenerated file 29.05.2009 15:17
// $Id: $
// $Log: $
//
//
require_once 'EbatNs_FacetType.php';

class FlatShippingRateOptionCodeType extends EbatNs_FacetType
{
	// start props
	// @var string $ChargeAmountForEachAdditionalItem
	var $ChargeAmountForEachAdditionalItem = 'ChargeAmountForEachAdditionalItem';
	// @var string $DeductAmountFromEachAdditionalItem
	var $DeductAmountFromEachAdditionalItem = 'DeductAmountFromEachAdditionalItem';
	// @var string $ShipAdditionalItemsFree
	var $ShipAdditionalItemsFree = 'ShipAdditionalItemsFree';
	// @var string $CustomCode
	var $CustomCode = 'CustomCode';
	// end props

/**
 *

 * @return 
 */
	function FlatShippingRateOptionCodeType()
	{
		$this->EbatNs_FacetType('FlatShippingRateOptionCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_FlatShippingRateOptionCodeType = new FlatShippingRateOptionCodeType();

?>
