<?php
// autogenerated file 29.05.2009 15:17
// $Id: $
// $Log: $
//
//
require_once 'EbatNs_FacetType.php';

class GallerySortFilterCodeType extends EbatNs_FacetType
{
	// start props
	// @var string $ShowAnyItems
	var $ShowAnyItems = 'ShowAnyItems';
	// @var string $ShowItemsWithGalleryImagesFirst
	var $ShowItemsWithGalleryImagesFirst = 'ShowItemsWithGalleryImagesFirst';
	// @var string $ShowOnlyItemsWithGalleryImages
	var $ShowOnlyItemsWithGalleryImages = 'ShowOnlyItemsWithGalleryImages';
	// @var string $CustomCode
	var $CustomCode = 'CustomCode';
	// end props

/**
 *

 * @return 
 */
	function GallerySortFilterCodeType()
	{
		$this->EbatNs_FacetType('GallerySortFilterCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_GallerySortFilterCodeType = new GallerySortFilterCodeType();

?>
