<?php
// autogenerated file 29.05.2009 15:17
// $Id: $
// $Log: $
//
//
require_once 'FeedbackSummaryType.php';
require_once 'AbstractResponseType.php';
require_once 'PaginationResultType.php';
require_once 'FeedbackDetailArrayType.php';

class GetFeedbackResponseType extends AbstractResponseType
{
	// start props
	// @var FeedbackDetailArrayType $FeedbackDetailArray
	var $FeedbackDetailArray;
	// @var int $FeedbackDetailItemTotal
	var $FeedbackDetailItemTotal;
	// @var FeedbackSummaryType $FeedbackSummary
	var $FeedbackSummary;
	// @var int $FeedbackScore
	var $FeedbackScore;
	// @var PaginationResultType $PaginationResult
	var $PaginationResult;
	// @var int $EntriesPerPage
	var $EntriesPerPage;
	// @var int $PageNumber
	var $PageNumber;
	// end props

/**
 *

 * @return FeedbackDetailArrayType
 */
	function getFeedbackDetailArray()
	{
		return $this->FeedbackDetailArray;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setFeedbackDetailArray($value)
	{
		$this->FeedbackDetailArray = $value;
	}
/**
 *

 * @return int
 */
	function getFeedbackDetailItemTotal()
	{
		return $this->FeedbackDetailItemTotal;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setFeedbackDetailItemTotal($value)
	{
		$this->FeedbackDetailItemTotal = $value;
	}
/**
 *

 * @return FeedbackSummaryType
 */
	function getFeedbackSummary()
	{
		return $this->FeedbackSummary;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setFeedbackSummary($value)
	{
		$this->FeedbackSummary = $value;
	}
/**
 *

 * @return int
 */
	function getFeedbackScore()
	{
		return $this->FeedbackScore;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setFeedbackScore($value)
	{
		$this->FeedbackScore = $value;
	}
/**
 *

 * @return PaginationResultType
 */
	function getPaginationResult()
	{
		return $this->PaginationResult;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setPaginationResult($value)
	{
		$this->PaginationResult = $value;
	}
/**
 *

 * @return int
 */
	function getEntriesPerPage()
	{
		return $this->EntriesPerPage;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setEntriesPerPage($value)
	{
		$this->EntriesPerPage = $value;
	}
/**
 *

 * @return int
 */
	function getPageNumber()
	{
		return $this->PageNumber;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setPageNumber($value)
	{
		$this->PageNumber = $value;
	}
/**
 *

 * @return 
 */
	function GetFeedbackResponseType()
	{
		$this->AbstractResponseType('GetFeedbackResponseType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'FeedbackDetailArray' =>
				array(
					'required' => false,
					'type' => 'FeedbackDetailArrayType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'FeedbackDetailItemTotal' =>
				array(
					'required' => false,
					'type' => 'int',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'FeedbackSummary' =>
				array(
					'required' => false,
					'type' => 'FeedbackSummaryType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'FeedbackScore' =>
				array(
					'required' => false,
					'type' => 'int',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'PaginationResult' =>
				array(
					'required' => false,
					'type' => 'PaginationResultType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'EntriesPerPage' =>
				array(
					'required' => false,
					'type' => 'int',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'PageNumber' =>
				array(
					'required' => false,
					'type' => 'int',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				)
			));

	}
}
?>
