<?php
// autogenerated file 29.05.2009 15:17
// $Id: $
// $Log: $
//
//
require_once 'NotificationRoleCodeType.php';
require_once 'AbstractRequestType.php';

class GetNotificationPreferencesRequestType extends AbstractRequestType
{
	// start props
	// @var NotificationRoleCodeType $PreferenceLevel
	var $PreferenceLevel;
	// end props

/**
 *

 * @return NotificationRoleCodeType
 */
	function getPreferenceLevel()
	{
		return $this->PreferenceLevel;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setPreferenceLevel($value)
	{
		$this->PreferenceLevel = $value;
	}
/**
 *

 * @return 
 */
	function GetNotificationPreferencesRequestType()
	{
		$this->AbstractRequestType('GetNotificationPreferencesRequestType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'PreferenceLevel' =>
				array(
					'required' => false,
					'type' => 'NotificationRoleCodeType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				)
			));

	}
}
?>
