<?php
// autogenerated file 29.05.2009 15:17
// $Id: $
// $Log: $
//
//
require_once 'AbstractRequestType.php';

class GetPictureManagerOptionsRequestType extends AbstractRequestType
{
	// start props
	// end props

/**
 *

 * @return 
 */
	function GetPictureManagerOptionsRequestType()
	{
		$this->AbstractRequestType('GetPictureManagerOptionsRequestType', 'urn:ebay:apis:eBLBaseComponents');

	}
}
?>
