<?php
// autogenerated file 29.05.2009 15:17
// $Id: $
// $Log: $
//
//
require_once 'ProductSearchType.php';
require_once 'AbstractRequestType.php';

class GetProductFamilyMembersRequestType extends AbstractRequestType
{
	// start props
	// @var ProductSearchType $ProductSearch
	var $ProductSearch;
	// end props

/**
 *

 * @return ProductSearchType
 * @param  $index 
 */
	function getProductSearch($index = null)
	{
		if ($index) {
		return $this->ProductSearch[$index];
	} else {
		return $this->ProductSearch;
	}

	}
/**
 *

 * @return void
 * @param  $value 
 * @param  $index 
 */
	function setProductSearch($value, $index = null)
	{
		if ($index) {
	$this->ProductSearch[$index] = $value;
	} else {
	$this->ProductSearch = $value;
	}

	}
/**
 *

 * @return 
 */
	function GetProductFamilyMembersRequestType()
	{
		$this->AbstractRequestType('GetProductFamilyMembersRequestType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'ProductSearch' =>
				array(
					'required' => false,
					'type' => 'ProductSearchType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => true,
					'cardinality' => '0..*'
				)
			));

	}
}
?>
