<?php
// autogenerated file 29.05.2009 15:17
// $Id: $
// $Log: $
//
//
require_once 'RecommendationEngineCodeType.php';
require_once 'EbatNs_ComplexType.php';
require_once 'ItemType.php';
require_once 'ListingFlowCodeType.php';

class GetRecommendationsRequestContainerType extends EbatNs_ComplexType
{
	// start props
	// @var ListingFlowCodeType $ListingFlow
	var $ListingFlow;
	// @var ItemType $Item
	var $Item;
	// @var RecommendationEngineCodeType $RecommendationEngine
	var $RecommendationEngine;
	// @var string $Query
	var $Query;
	// @var string $CorrelationID
	var $CorrelationID;
	// @var string $DeletedField
	var $DeletedField;
	// @var boolean $ExcludeRelationships
	var $ExcludeRelationships;
	// @var boolean $IncludeConfidence
	var $IncludeConfidence;
	// end props

/**
 *

 * @return ListingFlowCodeType
 */
	function getListingFlow()
	{
		return $this->ListingFlow;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setListingFlow($value)
	{
		$this->ListingFlow = $value;
	}
/**
 *

 * @return ItemType
 */
	function getItem()
	{
		return $this->Item;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setItem($value)
	{
		$this->Item = $value;
	}
/**
 *

 * @return RecommendationEngineCodeType
 * @param  $index 
 */
	function getRecommendationEngine($index = null)
	{
		if ($index) {
		return $this->RecommendationEngine[$index];
	} else {
		return $this->RecommendationEngine;
	}

	}
/**
 *

 * @return void
 * @param  $value 
 * @param  $index 
 */
	function setRecommendationEngine($value, $index = null)
	{
		if ($index) {
	$this->RecommendationEngine[$index] = $value;
	} else {
	$this->RecommendationEngine = $value;
	}

	}
/**
 *

 * @return string
 */
	function getQuery()
	{
		return $this->Query;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setQuery($value)
	{
		$this->Query = $value;
	}
/**
 *

 * @return string
 */
	function getCorrelationID()
	{
		return $this->CorrelationID;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setCorrelationID($value)
	{
		$this->CorrelationID = $value;
	}
/**
 *

 * @return string
 * @param  $index 
 */
	function getDeletedField($index = null)
	{
		if ($index) {
		return $this->DeletedField[$index];
	} else {
		return $this->DeletedField;
	}

	}
/**
 *

 * @return void
 * @param  $value 
 * @param  $index 
 */
	function setDeletedField($value, $index = null)
	{
		if ($index) {
	$this->DeletedField[$index] = $value;
	} else {
	$this->DeletedField = $value;
	}

	}
/**
 *

 * @return boolean
 */
	function getExcludeRelationships()
	{
		return $this->ExcludeRelationships;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setExcludeRelationships($value)
	{
		$this->ExcludeRelationships = $value;
	}
/**
 *

 * @return boolean
 */
	function getIncludeConfidence()
	{
		return $this->IncludeConfidence;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setIncludeConfidence($value)
	{
		$this->IncludeConfidence = $value;
	}
/**
 *

 * @return 
 */
	function GetRecommendationsRequestContainerType()
	{
		$this->EbatNs_ComplexType('GetRecommendationsRequestContainerType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'ListingFlow' =>
				array(
					'required' => false,
					'type' => 'ListingFlowCodeType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'Item' =>
				array(
					'required' => false,
					'type' => 'ItemType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'RecommendationEngine' =>
				array(
					'required' => false,
					'type' => 'RecommendationEngineCodeType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => true,
					'cardinality' => '0..*'
				),
				'Query' =>
				array(
					'required' => false,
					'type' => 'string',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'CorrelationID' =>
				array(
					'required' => false,
					'type' => 'string',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'DeletedField' =>
				array(
					'required' => false,
					'type' => 'string',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => true,
					'cardinality' => '0..*'
				),
				'ExcludeRelationships' =>
				array(
					'required' => false,
					'type' => 'boolean',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'IncludeConfidence' =>
				array(
					'required' => false,
					'type' => 'boolean',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				)
			));

	}
}
?>
