<?php
// autogenerated file 29.05.2009 15:17
// $Id: $
// $Log: $
//
//
require_once 'AbstractRequestType.php';

class GetStoreCategoryUpdateStatusRequestType extends AbstractRequestType
{
	// start props
	// @var long $TaskID
	var $TaskID;
	// end props

/**
 *

 * @return long
 */
	function getTaskID()
	{
		return $this->TaskID;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setTaskID($value)
	{
		$this->TaskID = $value;
	}
/**
 *

 * @return 
 */
	function GetStoreCategoryUpdateStatusRequestType()
	{
		$this->AbstractRequestType('GetStoreCategoryUpdateStatusRequestType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'TaskID' =>
				array(
					'required' => false,
					'type' => 'long',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				)
			));

	}
}
?>
