<?php
// autogenerated file 29.05.2009 15:17
// $Id: $
// $Log: $
//
//
require_once 'TaskStatusCodeType.php';
require_once 'AbstractResponseType.php';

class GetStoreCategoryUpdateStatusResponseType extends AbstractResponseType
{
	// start props
	// @var TaskStatusCodeType $Status
	var $Status;
	// end props

/**
 *

 * @return TaskStatusCodeType
 */
	function getStatus()
	{
		return $this->Status;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setStatus($value)
	{
		$this->Status = $value;
	}
/**
 *

 * @return 
 */
	function GetStoreCategoryUpdateStatusResponseType()
	{
		$this->AbstractResponseType('GetStoreCategoryUpdateStatusResponseType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'Status' =>
				array(
					'required' => false,
					'type' => 'TaskStatusCodeType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				)
			));

	}
}
?>
