<?php
// autogenerated file 29.05.2009 15:17
// $Id: $
// $Log: $
//
//
require_once 'SellingManagerInventoryPropertyTypeCodeType.php';
require_once 'PaginationType.php';
require_once 'SellingManagerProductSortCodeType.php';
require_once 'SortOrderCodeType.php';
require_once 'AbstractRequestType.php';
require_once 'SellingManagerSearchType.php';

class GetSellingManagerInventoryRequestType extends AbstractRequestType
{
	// start props
	// @var SellingManagerProductSortCodeType $Sort
	var $Sort;
	// @var long $FolderID
	var $FolderID;
	// @var PaginationType $Pagination
	var $Pagination;
	// @var SortOrderCodeType $SortOrder
	var $SortOrder;
	// @var SellingManagerSearchType $Search
	var $Search;
	// @var long $StoreCategoryID
	var $StoreCategoryID;
	// @var SellingManagerInventoryPropertyTypeCodeType $Filter
	var $Filter;
	// end props

/**
 *

 * @return SellingManagerProductSortCodeType
 */
	function getSort()
	{
		return $this->Sort;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setSort($value)
	{
		$this->Sort = $value;
	}
/**
 *

 * @return long
 */
	function getFolderID()
	{
		return $this->FolderID;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setFolderID($value)
	{
		$this->FolderID = $value;
	}
/**
 *

 * @return PaginationType
 */
	function getPagination()
	{
		return $this->Pagination;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setPagination($value)
	{
		$this->Pagination = $value;
	}
/**
 *

 * @return SortOrderCodeType
 */
	function getSortOrder()
	{
		return $this->SortOrder;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setSortOrder($value)
	{
		$this->SortOrder = $value;
	}
/**
 *

 * @return SellingManagerSearchType
 */
	function getSearch()
	{
		return $this->Search;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setSearch($value)
	{
		$this->Search = $value;
	}
/**
 *

 * @return long
 */
	function getStoreCategoryID()
	{
		return $this->StoreCategoryID;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setStoreCategoryID($value)
	{
		$this->StoreCategoryID = $value;
	}
/**
 *

 * @return SellingManagerInventoryPropertyTypeCodeType
 * @param  $index 
 */
	function getFilter($index = null)
	{
		if ($index) {
		return $this->Filter[$index];
	} else {
		return $this->Filter;
	}

	}
/**
 *

 * @return void
 * @param  $value 
 * @param  $index 
 */
	function setFilter($value, $index = null)
	{
		if ($index) {
	$this->Filter[$index] = $value;
	} else {
	$this->Filter = $value;
	}

	}
/**
 *

 * @return 
 */
	function GetSellingManagerInventoryRequestType()
	{
		$this->AbstractRequestType('GetSellingManagerInventoryRequestType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'Sort' =>
				array(
					'required' => false,
					'type' => 'SellingManagerProductSortCodeType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'FolderID' =>
				array(
					'required' => false,
					'type' => 'long',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'Pagination' =>
				array(
					'required' => false,
					'type' => 'PaginationType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'SortOrder' =>
				array(
					'required' => false,
					'type' => 'SortOrderCodeType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'Search' =>
				array(
					'required' => false,
					'type' => 'SellingManagerSearchType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'StoreCategoryID' =>
				array(
					'required' => false,
					'type' => 'long',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'Filter' =>
				array(
					'required' => false,
					'type' => 'SellingManagerInventoryPropertyTypeCodeType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => true,
					'cardinality' => '0..*'
				)
			));

	}
}
?>
