<?php
// autogenerated file 29.05.2009 15:17
// $Id: $
// $Log: $
//
//
require_once 'AbstractResponseType.php';
require_once 'SellingManagerTemplateDetailsArrayType.php';

class GetSellingManagerTemplatesResponseType extends AbstractResponseType
{
	// start props
	// @var SellingManagerTemplateDetailsArrayType $SellingManagerTemplateDetailsArray
	var $SellingManagerTemplateDetailsArray;
	// end props

/**
 *

 * @return SellingManagerTemplateDetailsArrayType
 */
	function getSellingManagerTemplateDetailsArray()
	{
		return $this->SellingManagerTemplateDetailsArray;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setSellingManagerTemplateDetailsArray($value)
	{
		$this->SellingManagerTemplateDetailsArray = $value;
	}
/**
 *

 * @return 
 */
	function GetSellingManagerTemplatesResponseType()
	{
		$this->AbstractResponseType('GetSellingManagerTemplatesResponseType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'SellingManagerTemplateDetailsArray' =>
				array(
					'required' => false,
					'type' => 'SellingManagerTemplateDetailsArrayType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				)
			));

	}
}
?>
