<?php
// autogenerated file 29.05.2009 15:17
// $Id: $
// $Log: $
//
//
require_once 'AbstractResponseType.php';
require_once 'UserType.php';

class GetUserResponseType extends AbstractResponseType
{
	// start props
	// @var UserType $User
	var $User;
	// end props

/**
 *

 * @return UserType
 */
	function getUser()
	{
		return $this->User;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setUser($value)
	{
		$this->User = $value;
	}
/**
 *

 * @return 
 */
	function GetUserResponseType()
	{
		$this->AbstractResponseType('GetUserResponseType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'User' =>
				array(
					'required' => false,
					'type' => 'UserType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				)
			));

	}
}
?>
