<?php
// autogenerated file 29.05.2009 15:17
// $Id: $
// $Log: $
//
//
require_once 'EbatNs_FacetType.php';

class GranularityLevelCodeType extends EbatNs_FacetType
{
	// start props
	// @var string $Coarse
	var $Coarse = 'Coarse';
	// @var string $Fine
	var $Fine = 'Fine';
	// @var string $Medium
	var $Medium = 'Medium';
	// @var string $CustomCode
	var $CustomCode = 'CustomCode';
	// end props

/**
 *

 * @return 
 */
	function GranularityLevelCodeType()
	{
		$this->EbatNs_FacetType('GranularityLevelCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_GranularityLevelCodeType = new GranularityLevelCodeType();

?>
