<?php
// autogenerated file 29.05.2009 15:17
// $Id: $
// $Log: $
//
//
require_once 'EbatNs_FacetType.php';

class INEscrowWorkflowTimelineCodeType extends EbatNs_FacetType
{
	// start props
	// @var string $Default
	var $Default = 'Default';
	// @var string $WorkflowA
	var $WorkflowA = 'WorkflowA';
	// @var string $WorkflowB
	var $WorkflowB = 'WorkflowB';
	// @var string $CustomCode
	var $CustomCode = 'CustomCode';
	// end props

/**
 *

 * @return 
 */
	function INEscrowWorkflowTimelineCodeType()
	{
		$this->EbatNs_FacetType('INEscrowWorkflowTimelineCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_INEscrowWorkflowTimelineCodeType = new INEscrowWorkflowTimelineCodeType();

?>
