<?php
// autogenerated file 29.05.2009 15:17
// $Id: $
// $Log: $
//
//
require_once 'EbatNs_FacetType.php';

class ListingEnhancementDurationCodeType extends EbatNs_FacetType
{
	// start props
	// @var string $Days_1
	var $Days_1 = 'Days_1';
	// @var string $Days_2
	var $Days_2 = 'Days_2';
	// @var string $Days_3
	var $Days_3 = 'Days_3';
	// @var string $Days_4
	var $Days_4 = 'Days_4';
	// @var string $Days_5
	var $Days_5 = 'Days_5';
	// @var string $Days_6
	var $Days_6 = 'Days_6';
	// @var string $Days_7
	var $Days_7 = 'Days_7';
	// @var string $Days_8
	var $Days_8 = 'Days_8';
	// @var string $Days_9
	var $Days_9 = 'Days_9';
	// @var string $Days_10
	var $Days_10 = 'Days_10';
	// @var string $Days_11
	var $Days_11 = 'Days_11';
	// @var string $Days_12
	var $Days_12 = 'Days_12';
	// @var string $Days_13
	var $Days_13 = 'Days_13';
	// @var string $Days_14
	var $Days_14 = 'Days_14';
	// @var string $Days_15
	var $Days_15 = 'Days_15';
	// @var string $Days_16
	var $Days_16 = 'Days_16';
	// @var string $Days_17
	var $Days_17 = 'Days_17';
	// @var string $Days_18
	var $Days_18 = 'Days_18';
	// @var string $Days_19
	var $Days_19 = 'Days_19';
	// @var string $Days_20
	var $Days_20 = 'Days_20';
	// @var string $Days_21
	var $Days_21 = 'Days_21';
	// @var string $Days_22
	var $Days_22 = 'Days_22';
	// @var string $Days_23
	var $Days_23 = 'Days_23';
	// @var string $Days_24
	var $Days_24 = 'Days_24';
	// @var string $Days_25
	var $Days_25 = 'Days_25';
	// @var string $Days_26
	var $Days_26 = 'Days_26';
	// @var string $Days_27
	var $Days_27 = 'Days_27';
	// @var string $Days_28
	var $Days_28 = 'Days_28';
	// @var string $Days_29
	var $Days_29 = 'Days_29';
	// @var string $Days_30
	var $Days_30 = 'Days_30';
	// @var string $Days_31
	var $Days_31 = 'Days_31';
	// @var string $Days_32
	var $Days_32 = 'Days_32';
	// @var string $Days_33
	var $Days_33 = 'Days_33';
	// @var string $Days_34
	var $Days_34 = 'Days_34';
	// @var string $Days_35
	var $Days_35 = 'Days_35';
	// @var string $Days_36
	var $Days_36 = 'Days_36';
	// @var string $Days_37
	var $Days_37 = 'Days_37';
	// @var string $Days_38
	var $Days_38 = 'Days_38';
	// @var string $Days_39
	var $Days_39 = 'Days_39';
	// @var string $Days_40
	var $Days_40 = 'Days_40';
	// @var string $Days_41
	var $Days_41 = 'Days_41';
	// @var string $Days_42
	var $Days_42 = 'Days_42';
	// @var string $Days_43
	var $Days_43 = 'Days_43';
	// @var string $Days_44
	var $Days_44 = 'Days_44';
	// @var string $Days_45
	var $Days_45 = 'Days_45';
	// @var string $Days_46
	var $Days_46 = 'Days_46';
	// @var string $Days_47
	var $Days_47 = 'Days_47';
	// @var string $Days_48
	var $Days_48 = 'Days_48';
	// @var string $Days_49
	var $Days_49 = 'Days_49';
	// @var string $Days_50
	var $Days_50 = 'Days_50';
	// @var string $Lifetime
	var $Lifetime = 'Lifetime';
	// @var string $CustomCode
	var $CustomCode = 'CustomCode';
	// end props

/**
 *

 * @return 
 */
	function ListingEnhancementDurationCodeType()
	{
		$this->EbatNs_FacetType('ListingEnhancementDurationCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_ListingEnhancementDurationCodeType = new ListingEnhancementDurationCodeType();

?>
