<?php
// autogenerated file 29.05.2009 15:17
// $Id: $
// $Log: $
//
//
require_once 'EbatNs_ComplexType.php';

class MaximumItemRequirementsDetailsType extends EbatNs_ComplexType
{
	// start props
	// @var int $MaximumItemCount
	var $MaximumItemCount;
	// @var int $MinimumFeedbackScore
	var $MinimumFeedbackScore;
	// end props

/**
 *

 * @return int
 * @param  $index 
 */
	function getMaximumItemCount($index = null)
	{
		if ($index) {
		return $this->MaximumItemCount[$index];
	} else {
		return $this->MaximumItemCount;
	}

	}
/**
 *

 * @return void
 * @param  $value 
 * @param  $index 
 */
	function setMaximumItemCount($value, $index = null)
	{
		if ($index) {
	$this->MaximumItemCount[$index] = $value;
	} else {
	$this->MaximumItemCount = $value;
	}

	}
/**
 *

 * @return int
 * @param  $index 
 */
	function getMinimumFeedbackScore($index = null)
	{
		if ($index) {
		return $this->MinimumFeedbackScore[$index];
	} else {
		return $this->MinimumFeedbackScore;
	}

	}
/**
 *

 * @return void
 * @param  $value 
 * @param  $index 
 */
	function setMinimumFeedbackScore($value, $index = null)
	{
		if ($index) {
	$this->MinimumFeedbackScore[$index] = $value;
	} else {
	$this->MinimumFeedbackScore = $value;
	}

	}
/**
 *

 * @return 
 */
	function MaximumItemRequirementsDetailsType()
	{
		$this->EbatNs_ComplexType('MaximumItemRequirementsDetailsType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'MaximumItemCount' =>
				array(
					'required' => false,
					'type' => 'int',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => true,
					'cardinality' => '0..*'
				),
				'MinimumFeedbackScore' =>
				array(
					'required' => false,
					'type' => 'int',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => true,
					'cardinality' => '0..*'
				)
			));

	}
}
?>
