<?php
// autogenerated file 29.05.2009 15:17
// $Id: $
// $Log: $
//
//
require_once 'EbatNs_SimpleType.php';

class MyMessagesExternalMessageIDType extends EbatNs_SimpleType
{
	// start props
	// end props

/**
 *

 * @return 
 */
	function MyMessagesExternalMessageIDType()
	{
		$this->EbatNs_SimpleType('MyMessagesExternalMessageIDType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_MyMessagesExternalMessageIDType = new MyMessagesExternalMessageIDType();

?>
