<?php
// autogenerated file 29.05.2009 15:17
// $Id: $
// $Log: $
//
//
require_once 'MyMessagesAlertIDType.php';
require_once 'EbatNs_ComplexType.php';

class MyMessagesAlertIDArrayType extends EbatNs_ComplexType
{
	// start props
	// @var MyMessagesAlertIDType $AlertID
	var $AlertID;
	// end props

/**
 *

 * @return MyMessagesAlertIDType
 * @param  $index 
 */
	function getAlertID($index = null)
	{
		if ($index) {
		return $this->AlertID[$index];
	} else {
		return $this->AlertID;
	}

	}
/**
 *

 * @return void
 * @param  $value 
 * @param  $index 
 */
	function setAlertID($value, $index = null)
	{
		if ($index) {
	$this->AlertID[$index] = $value;
	} else {
	$this->AlertID = $value;
	}

	}
/**
 *

 * @return 
 */
	function MyMessagesAlertIDArrayType()
	{
		$this->EbatNs_ComplexType('MyMessagesAlertIDArrayType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'AlertID' =>
				array(
					'required' => false,
					'type' => 'MyMessagesAlertIDType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => true,
					'cardinality' => '0..*'
				)
			));

	}
}
?>
