<?php
// autogenerated file 29.05.2009 15:17
// $Id: $
// $Log: $
//
//
require_once 'EbatNs_SimpleType.php';

class MyMessagesMessageIDType extends EbatNs_SimpleType
{
	// start props
	// end props

/**
 *

 * @return 
 */
	function MyMessagesMessageIDType()
	{
		$this->EbatNs_SimpleType('MyMessagesMessageIDType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_MyMessagesMessageIDType = new MyMessagesMessageIDType();

?>
