<?php
// autogenerated file 29.05.2009 15:17
// $Id: $
// $Log: $
//
//
require_once 'EbatNs_FacetType.php';

class MyMessagesFolderOperationCodeType extends EbatNs_FacetType
{
	// start props
	// @var string $Display
	var $Display = 'Display';
	// @var string $Rename
	var $Rename = 'Rename';
	// @var string $Remove
	var $Remove = 'Remove';
	// @var string $CustomCode
	var $CustomCode = 'CustomCode';
	// end props

/**
 *

 * @return 
 */
	function MyMessagesFolderOperationCodeType()
	{
		$this->EbatNs_FacetType('MyMessagesFolderOperationCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_MyMessagesFolderOperationCodeType = new MyMessagesFolderOperationCodeType();

?>
