<?php
// autogenerated file 29.05.2009 15:17
// $Id: $
// $Log: $
//
//
require_once 'ValueRecommendationType.php';
require_once 'EbatNs_ComplexType.php';
require_once 'ItemSpecificSourceCodeType.php';
require_once 'RecommendationValidationRulesType.php';

class NameRecommendationType extends EbatNs_ComplexType
{
	// start props
	// @var string $Name
	var $Name;
	// @var RecommendationValidationRulesType $ValidationRules
	var $ValidationRules;
	// @var ValueRecommendationType $ValueRecommendation
	var $ValueRecommendation;
	// @var anyURI $HelpURL
	var $HelpURL;
	// @var ItemSpecificSourceCodeType $Source
	var $Source;
	// end props

/**
 *

 * @return string
 */
	function getName()
	{
		return $this->Name;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setName($value)
	{
		$this->Name = $value;
	}
/**
 *

 * @return RecommendationValidationRulesType
 */
	function getValidationRules()
	{
		return $this->ValidationRules;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setValidationRules($value)
	{
		$this->ValidationRules = $value;
	}
/**
 *

 * @return ValueRecommendationType
 * @param  $index 
 */
	function getValueRecommendation($index = null)
	{
		if ($index) {
		return $this->ValueRecommendation[$index];
	} else {
		return $this->ValueRecommendation;
	}

	}
/**
 *

 * @return void
 * @param  $value 
 * @param  $index 
 */
	function setValueRecommendation($value, $index = null)
	{
		if ($index) {
	$this->ValueRecommendation[$index] = $value;
	} else {
	$this->ValueRecommendation = $value;
	}

	}
/**
 *

 * @return anyURI
 */
	function getHelpURL()
	{
		return $this->HelpURL;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setHelpURL($value)
	{
		$this->HelpURL = $value;
	}
/**
 *

 * @return ItemSpecificSourceCodeType
 */
	function getSource()
	{
		return $this->Source;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setSource($value)
	{
		$this->Source = $value;
	}
/**
 *

 * @return 
 */
	function NameRecommendationType()
	{
		$this->EbatNs_ComplexType('NameRecommendationType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'Name' =>
				array(
					'required' => false,
					'type' => 'string',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'ValidationRules' =>
				array(
					'required' => false,
					'type' => 'RecommendationValidationRulesType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'ValueRecommendation' =>
				array(
					'required' => false,
					'type' => 'ValueRecommendationType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => true,
					'cardinality' => '0..*'
				),
				'HelpURL' =>
				array(
					'required' => false,
					'type' => 'anyURI',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'Source' =>
				array(
					'required' => false,
					'type' => 'ItemSpecificSourceCodeType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				)
			));

	}
}
?>
