<?php
// autogenerated file 29.05.2009 15:17
// $Id: $
// $Log: $
//
//
require_once 'EbatNs_SimpleType.php';

class OrderIDType extends EbatNs_SimpleType
{
	// start props
	// end props

/**
 *

 * @return 
 */
	function OrderIDType()
	{
		$this->EbatNs_SimpleType('OrderIDType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_OrderIDType = new OrderIDType();

?>
