<?php
// autogenerated file 29.05.2009 15:17
// $Id: $
// $Log: $
//
//
require_once 'EbatNs_FacetType.php';

class PaidStatusCodeType extends EbatNs_FacetType
{
	// start props
	// @var string $NotPaid
	var $NotPaid = 'NotPaid';
	// @var string $BuyerHasNotCompletedCheckout
	var $BuyerHasNotCompletedCheckout = 'BuyerHasNotCompletedCheckout';
	// @var string $PaymentPendingWithPayPal
	var $PaymentPendingWithPayPal = 'PaymentPendingWithPayPal';
	// @var string $PaidWithPayPal
	var $PaidWithPayPal = 'PaidWithPayPal';
	// @var string $MarkedAsPaid
	var $MarkedAsPaid = 'MarkedAsPaid';
	// @var string $PaymentPendingWithEscrow
	var $PaymentPendingWithEscrow = 'PaymentPendingWithEscrow';
	// @var string $PaidWithEscrow
	var $PaidWithEscrow = 'PaidWithEscrow';
	// @var string $EscrowPaymentCancelled
	var $EscrowPaymentCancelled = 'EscrowPaymentCancelled';
	// @var string $PaymentPendingWithPaisaPay
	var $PaymentPendingWithPaisaPay = 'PaymentPendingWithPaisaPay';
	// @var string $PaidWithPaisaPay
	var $PaidWithPaisaPay = 'PaidWithPaisaPay';
	// @var string $PaymentPending
	var $PaymentPending = 'PaymentPending';
	// @var string $PaymentPendingWithPaisaPayEscrow
	var $PaymentPendingWithPaisaPayEscrow = 'PaymentPendingWithPaisaPayEscrow';
	// @var string $PaidWithPaisaPayEscrow
	var $PaidWithPaisaPayEscrow = 'PaidWithPaisaPayEscrow';
	// @var string $PaisaPayNotPaid
	var $PaisaPayNotPaid = 'PaisaPayNotPaid';
	// @var string $Refunded
	var $Refunded = 'Refunded';
	// @var string $WaitingForCODPayment
	var $WaitingForCODPayment = 'WaitingForCODPayment';
	// @var string $PaidCOD
	var $PaidCOD = 'PaidCOD';
	// @var string $CustomCode
	var $CustomCode = 'CustomCode';
	// end props

/**
 *

 * @return 
 */
	function PaidStatusCodeType()
	{
		$this->EbatNs_FacetType('PaidStatusCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_PaidStatusCodeType = new PaidStatusCodeType();

?>
