<?php
// autogenerated file 29.05.2009 15:17
// $Id: $
// $Log: $
//
//
require_once 'EbatNs_ComplexType.php';
require_once 'VariationSpecificPictureSetType.php';

class PicturesType extends EbatNs_ComplexType
{
	// start props
	// @var string $VariationSpecificName
	var $VariationSpecificName;
	// @var VariationSpecificPictureSetType $VariationSpecificPictureSet
	var $VariationSpecificPictureSet;
	// end props

/**
 *

 * @return string
 */
	function getVariationSpecificName()
	{
		return $this->VariationSpecificName;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setVariationSpecificName($value)
	{
		$this->VariationSpecificName = $value;
	}
/**
 *

 * @return VariationSpecificPictureSetType
 * @param  $index 
 */
	function getVariationSpecificPictureSet($index = null)
	{
		if ($index) {
		return $this->VariationSpecificPictureSet[$index];
	} else {
		return $this->VariationSpecificPictureSet;
	}

	}
/**
 *

 * @return void
 * @param  $value 
 * @param  $index 
 */
	function setVariationSpecificPictureSet($value, $index = null)
	{
		if ($index) {
	$this->VariationSpecificPictureSet[$index] = $value;
	} else {
	$this->VariationSpecificPictureSet = $value;
	}

	}
/**
 *

 * @return 
 */
	function PicturesType()
	{
		$this->EbatNs_ComplexType('PicturesType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'VariationSpecificName' =>
				array(
					'required' => false,
					'type' => 'string',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'VariationSpecificPictureSet' =>
				array(
					'required' => false,
					'type' => 'VariationSpecificPictureSetType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => true,
					'cardinality' => '0..*'
				)
			));

	}
}
?>
