<?php
// autogenerated file 29.05.2009 15:17
// $Id: $
// $Log: $
//
//
require_once 'EbatNs_FacetType.php';

class ProductUseCaseCodeType extends EbatNs_FacetType
{
	// start props
	// @var string $AddItem
	var $AddItem = 'AddItem';
	// @var string $ReviseItem
	var $ReviseItem = 'ReviseItem';
	// @var string $RelistItem
	var $RelistItem = 'RelistItem';
	// @var string $CustomCode
	var $CustomCode = 'CustomCode';
	// end props

/**
 *

 * @return 
 */
	function ProductUseCaseCodeType()
	{
		$this->EbatNs_FacetType('ProductUseCaseCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_ProductUseCaseCodeType = new ProductUseCaseCodeType();

?>
