<?php
// autogenerated file 29.05.2009 15:17
// $Id: $
// $Log: $
//
//
require_once 'EbatNs_FacetType.php';

class PromotionMethodCodeType extends EbatNs_FacetType
{
	// start props
	// @var string $CrossSell
	var $CrossSell = 'CrossSell';
	// @var string $UpSell
	var $UpSell = 'UpSell';
	// @var string $CustomCode
	var $CustomCode = 'CustomCode';
	// end props

/**
 *

 * @return 
 */
	function PromotionMethodCodeType()
	{
		$this->EbatNs_FacetType('PromotionMethodCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_PromotionMethodCodeType = new PromotionMethodCodeType();

?>
