<?php
// autogenerated file 29.05.2009 15:17
// $Id: $
// $Log: $
//
//
require_once 'EbatNs_ComplexType.php';

class QuantityType extends EbatNs_ComplexType
{
	// start props
	// end props

/**
 *

 * @return 
 */
	function QuantityType()
	{
		$this->EbatNs_ComplexType('QuantityType', 'http://www.w3.org/2001/XMLSchema');
	$this->_attributes = array_merge($this->_attributes,
		array(
			'unit' =>
			array(
				'name' => 'unit',
				'type' => 'token',
				'use' => 'required'
			)
		));

	}
}
?>
