<?php
// autogenerated file 29.05.2009 15:17
// $Id: $
// $Log: $
//
//
require_once 'EbatNs_FacetType.php';

class RCSPaymentStatusCodeType extends EbatNs_FacetType
{
	// start props
	// @var string $Canceled
	var $Canceled = 'Canceled';
	// @var string $Paid
	var $Paid = 'Paid';
	// @var string $Pending
	var $Pending = 'Pending';
	// @var string $CustomCode
	var $CustomCode = 'CustomCode';
	// end props

/**
 *

 * @return 
 */
	function RCSPaymentStatusCodeType()
	{
		$this->EbatNs_FacetType('RCSPaymentStatusCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_RCSPaymentStatusCodeType = new RCSPaymentStatusCodeType();

?>
