<?php
// autogenerated file 29.05.2009 15:17
// $Id: $
// $Log: $
//
//
require_once 'EbatNs_FacetType.php';

class RefundOptionsCodeType extends EbatNs_FacetType
{
	// start props
	// @var string $MoneyBack
	var $MoneyBack = 'MoneyBack';
	// @var string $Exchange
	var $Exchange = 'Exchange';
	// @var string $MerchandiseCredit
	var $MerchandiseCredit = 'MerchandiseCredit';
	// @var string $CustomCode
	var $CustomCode = 'CustomCode';
	// end props

/**
 *

 * @return 
 */
	function RefundOptionsCodeType()
	{
		$this->EbatNs_FacetType('RefundOptionsCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_RefundOptionsCodeType = new RefundOptionsCodeType();

?>
