<?php
// autogenerated file 29.05.2009 15:17
// $Id: $
// $Log: $
//
//
require_once 'EbatNs_FacetType.php';

class ReturnsAcceptedOptionsCodeType extends EbatNs_FacetType
{
	// start props
	// @var string $ReturnsAccepted
	var $ReturnsAccepted = 'ReturnsAccepted';
	// @var string $ReturnsNotAccepted
	var $ReturnsNotAccepted = 'ReturnsNotAccepted';
	// @var string $CustomCode
	var $CustomCode = 'CustomCode';
	// end props

/**
 *

 * @return 
 */
	function ReturnsAcceptedOptionsCodeType()
	{
		$this->EbatNs_FacetType('ReturnsAcceptedOptionsCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_ReturnsAcceptedOptionsCodeType = new ReturnsAcceptedOptionsCodeType();

?>
