<?php
// autogenerated file 29.05.2009 15:17
// $Id: $
// $Log: $
//
//
require_once 'AbstractRequestType.php';

class RevokeTokenRequestType extends AbstractRequestType
{
	// start props
	// @var boolean $UnsubscribeNotification
	var $UnsubscribeNotification;
	// end props

/**
 *

 * @return boolean
 */
	function getUnsubscribeNotification()
	{
		return $this->UnsubscribeNotification;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setUnsubscribeNotification($value)
	{
		$this->UnsubscribeNotification = $value;
	}
/**
 *

 * @return 
 */
	function RevokeTokenRequestType()
	{
		$this->AbstractRequestType('RevokeTokenRequestType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'UnsubscribeNotification' =>
				array(
					'required' => false,
					'type' => 'boolean',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				)
			));

	}
}
?>
