<?php
// autogenerated file 29.05.2009 15:17
// $Id: $
// $Log: $
//
//
require_once 'EbatNs_FacetType.php';

class SearchFlagCodeType extends EbatNs_FacetType
{
	// start props
	// @var string $Charity
	var $Charity = 'Charity';
	// @var string $Gift
	var $Gift = 'Gift';
	// @var string $NowAndNew
	var $NowAndNew = 'NowAndNew';
	// @var string $LocalSearch
	var $LocalSearch = 'LocalSearch';
	// @var string $FreeShipping
	var $FreeShipping = 'FreeShipping';
	// @var string $Gallery
	var $Gallery = 'Gallery';
	// @var string $Picture
	var $Picture = 'Picture';
	// @var string $GetItFast
	var $GetItFast = 'GetItFast';
	// @var string $Lot
	var $Lot = 'Lot';
	// @var string $GermanMotorsSearchable
	var $GermanMotorsSearchable = 'GermanMotorsSearchable';
	// @var string $WorldOfGood
	var $WorldOfGood = 'WorldOfGood';
	// @var string $DigitalDelivery
	var $DigitalDelivery = 'DigitalDelivery';
	// @var string $CustomCode
	var $CustomCode = 'CustomCode';
	// end props

/**
 *

 * @return 
 */
	function SearchFlagCodeType()
	{
		$this->EbatNs_FacetType('SearchFlagCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_SearchFlagCodeType = new SearchFlagCodeType();

?>
