<?php
// autogenerated file 29.05.2009 15:17
// $Id: $
// $Log: $
//
//
require_once 'EbatNs_ComplexType.php';
require_once 'SearchStandingStatusCodeType.php';

class SearchStandingDashboardType extends EbatNs_ComplexType
{
	// start props
	// @var SearchStandingStatusCodeType $Status
	var $Status;
	// end props

/**
 *

 * @return SearchStandingStatusCodeType
 */
	function getStatus()
	{
		return $this->Status;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setStatus($value)
	{
		$this->Status = $value;
	}
/**
 *

 * @return 
 */
	function SearchStandingDashboardType()
	{
		$this->EbatNs_ComplexType('SearchStandingDashboardType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'Status' =>
				array(
					'required' => false,
					'type' => 'SearchStandingStatusCodeType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				)
			));

	}
}
?>
