<?php
// autogenerated file 29.05.2009 15:17
// $Id: $
// $Log: $
//
//
require_once 'EbatNs_FacetType.php';

class SellerPaymentMethodCodeType extends EbatNs_FacetType
{
	// start props
	// @var string $NothingOnFile
	var $NothingOnFile = 'NothingOnFile';
	// @var string $CreditCard
	var $CreditCard = 'CreditCard';
	// @var string $PayPal
	var $PayPal = 'PayPal';
	// @var string $DirectDebit
	var $DirectDebit = 'DirectDebit';
	// @var string $DirectDebitPendingSignatureMandate
	var $DirectDebitPendingSignatureMandate = 'DirectDebitPendingSignatureMandate';
	// @var string $eBayDirectPay
	var $eBayDirectPay = 'eBayDirectPay';
	// @var string $CustomCode
	var $CustomCode = 'CustomCode';
	// end props

/**
 *

 * @return 
 */
	function SellerPaymentMethodCodeType()
	{
		$this->EbatNs_FacetType('SellerPaymentMethodCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_SellerPaymentMethodCodeType = new SellerPaymentMethodCodeType();

?>
