<?php
// autogenerated file 29.05.2009 15:17
// $Id: $
// $Log: $
//
//
require_once 'SellerDashboardAlertSeverityCodeType.php';
require_once 'EbatNs_ComplexType.php';

class SellerDashboardAlertType extends EbatNs_ComplexType
{
	// start props
	// @var SellerDashboardAlertSeverityCodeType $Severity
	var $Severity;
	// @var string $Text
	var $Text;
	// end props

/**
 *

 * @return SellerDashboardAlertSeverityCodeType
 */
	function getSeverity()
	{
		return $this->Severity;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setSeverity($value)
	{
		$this->Severity = $value;
	}
/**
 *

 * @return string
 */
	function getText()
	{
		return $this->Text;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setText($value)
	{
		$this->Text = $value;
	}
/**
 *

 * @return 
 */
	function SellerDashboardAlertType()
	{
		$this->EbatNs_ComplexType('SellerDashboardAlertType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'Severity' =>
				array(
					'required' => false,
					'type' => 'SellerDashboardAlertSeverityCodeType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'Text' =>
				array(
					'required' => false,
					'type' => 'string',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				)
			));

	}
}
?>
