<?php
// autogenerated file 29.05.2009 15:17
// $Id: $
// $Log: $
//
//
require_once 'EbatNs_ComplexType.php';
require_once 'SellingManagerAutoListAccordingToScheduleType.php';
require_once 'SellingManagerAutoListMinActiveItemsType.php';

class SellingManagerAutoListType extends EbatNs_ComplexType
{
	// start props
	// @var long $SourceSaleTemplateID
	var $SourceSaleTemplateID;
	// @var SellingManagerAutoListMinActiveItemsType $KeepMinActive
	var $KeepMinActive;
	// @var SellingManagerAutoListAccordingToScheduleType $ListAccordingToSchedule
	var $ListAccordingToSchedule;
	// end props

/**
 *

 * @return long
 */
	function getSourceSaleTemplateID()
	{
		return $this->SourceSaleTemplateID;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setSourceSaleTemplateID($value)
	{
		$this->SourceSaleTemplateID = $value;
	}
/**
 *

 * @return SellingManagerAutoListMinActiveItemsType
 */
	function getKeepMinActive()
	{
		return $this->KeepMinActive;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setKeepMinActive($value)
	{
		$this->KeepMinActive = $value;
	}
/**
 *

 * @return SellingManagerAutoListAccordingToScheduleType
 */
	function getListAccordingToSchedule()
	{
		return $this->ListAccordingToSchedule;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setListAccordingToSchedule($value)
	{
		$this->ListAccordingToSchedule = $value;
	}
/**
 *

 * @return 
 */
	function SellingManagerAutoListType()
	{
		$this->EbatNs_ComplexType('SellingManagerAutoListType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'SourceSaleTemplateID' =>
				array(
					'required' => false,
					'type' => 'long',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'KeepMinActive' =>
				array(
					'required' => false,
					'type' => 'SellingManagerAutoListMinActiveItemsType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'ListAccordingToSchedule' =>
				array(
					'required' => false,
					'type' => 'SellingManagerAutoListAccordingToScheduleType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				)
			));

	}
}
?>
