<?php
// autogenerated file 29.05.2009 15:17
// $Id: $
// $Log: $
//
//
require_once 'SecondChanceOfferDurationCodeType.php';
require_once 'EbatNs_ComplexType.php';
require_once 'SellingManagerAutoSecondChanceOfferTypeCodeType.php';
require_once 'AmountType.php';

class SellingManagerAutoSecondChanceOfferType extends EbatNs_ComplexType
{
	// start props
	// @var SellingManagerAutoSecondChanceOfferTypeCodeType $SecondChanceOfferCondition
	var $SecondChanceOfferCondition;
	// @var AmountType $Amount
	var $Amount;
	// @var float $ProfitPercent
	var $ProfitPercent;
	// @var SecondChanceOfferDurationCodeType $Duration
	var $Duration;
	// @var int $ListingHoldInventoryLevel
	var $ListingHoldInventoryLevel;
	// end props

/**
 *

 * @return SellingManagerAutoSecondChanceOfferTypeCodeType
 */
	function getSecondChanceOfferCondition()
	{
		return $this->SecondChanceOfferCondition;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setSecondChanceOfferCondition($value)
	{
		$this->SecondChanceOfferCondition = $value;
	}
/**
 *

 * @return AmountType
 */
	function getAmount()
	{
		return $this->Amount;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setAmount($value)
	{
		$this->Amount = $value;
	}
/**
 *

 * @return float
 */
	function getProfitPercent()
	{
		return $this->ProfitPercent;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setProfitPercent($value)
	{
		$this->ProfitPercent = $value;
	}
/**
 *

 * @return SecondChanceOfferDurationCodeType
 */
	function getDuration()
	{
		return $this->Duration;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setDuration($value)
	{
		$this->Duration = $value;
	}
/**
 *

 * @return int
 */
	function getListingHoldInventoryLevel()
	{
		return $this->ListingHoldInventoryLevel;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setListingHoldInventoryLevel($value)
	{
		$this->ListingHoldInventoryLevel = $value;
	}
/**
 *

 * @return 
 */
	function SellingManagerAutoSecondChanceOfferType()
	{
		$this->EbatNs_ComplexType('SellingManagerAutoSecondChanceOfferType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'SecondChanceOfferCondition' =>
				array(
					'required' => false,
					'type' => 'SellingManagerAutoSecondChanceOfferTypeCodeType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'Amount' =>
				array(
					'required' => false,
					'type' => 'AmountType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'ProfitPercent' =>
				array(
					'required' => false,
					'type' => 'float',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'Duration' =>
				array(
					'required' => false,
					'type' => 'SecondChanceOfferDurationCodeType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'ListingHoldInventoryLevel' =>
				array(
					'required' => false,
					'type' => 'int',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				)
			));

	}
}
?>
