<?php
// autogenerated file 29.05.2009 15:17
// $Id: $
// $Log: $
//
//
require_once 'EbatNs_FacetType.php';

class SellerDashboardAlertSeverityCodeType extends EbatNs_FacetType
{
	// start props
	// @var string $Informational
	var $Informational = 'Informational';
	// @var string $Warning
	var $Warning = 'Warning';
	// @var string $StrongWarning
	var $StrongWarning = 'StrongWarning';
	// @var string $CustomCode
	var $CustomCode = 'CustomCode';
	// end props

/**
 *

 * @return 
 */
	function SellerDashboardAlertSeverityCodeType()
	{
		$this->EbatNs_FacetType('SellerDashboardAlertSeverityCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_SellerDashboardAlertSeverityCodeType = new SellerDashboardAlertSeverityCodeType();

?>
