<?php
// autogenerated file 29.05.2009 15:17
// $Id: $
// $Log: $
//
//
require_once 'EbatNs_ComplexType.php';
require_once 'SellingManagerAutoRelistOptionCodeType.php';
require_once 'BestOfferDetailsType.php';
require_once 'SellingManagerAutoRelistTypeCodeType.php';

class SellingManagerAutoRelistType extends EbatNs_ComplexType
{
	// start props
	// @var SellingManagerAutoRelistTypeCodeType $Type
	var $Type;
	// @var SellingManagerAutoRelistOptionCodeType $RelistCondition
	var $RelistCondition;
	// @var int $RelistAfterDays
	var $RelistAfterDays;
	// @var int $RelistAfterHours
	var $RelistAfterHours;
	// @var time $RelistAtSpecificTimeOfDay
	var $RelistAtSpecificTimeOfDay;
	// @var BestOfferDetailsType $BestOfferDetails
	var $BestOfferDetails;
	// @var int $ListingHoldInventoryLevel
	var $ListingHoldInventoryLevel;
	// end props

/**
 *

 * @return SellingManagerAutoRelistTypeCodeType
 */
	function getType()
	{
		return $this->Type;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setType($value)
	{
		$this->Type = $value;
	}
/**
 *

 * @return SellingManagerAutoRelistOptionCodeType
 */
	function getRelistCondition()
	{
		return $this->RelistCondition;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setRelistCondition($value)
	{
		$this->RelistCondition = $value;
	}
/**
 *

 * @return int
 */
	function getRelistAfterDays()
	{
		return $this->RelistAfterDays;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setRelistAfterDays($value)
	{
		$this->RelistAfterDays = $value;
	}
/**
 *

 * @return int
 */
	function getRelistAfterHours()
	{
		return $this->RelistAfterHours;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setRelistAfterHours($value)
	{
		$this->RelistAfterHours = $value;
	}
/**
 *

 * @return time
 */
	function getRelistAtSpecificTimeOfDay()
	{
		return $this->RelistAtSpecificTimeOfDay;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setRelistAtSpecificTimeOfDay($value)
	{
		$this->RelistAtSpecificTimeOfDay = $value;
	}
/**
 *

 * @return BestOfferDetailsType
 */
	function getBestOfferDetails()
	{
		return $this->BestOfferDetails;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setBestOfferDetails($value)
	{
		$this->BestOfferDetails = $value;
	}
/**
 *

 * @return int
 */
	function getListingHoldInventoryLevel()
	{
		return $this->ListingHoldInventoryLevel;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setListingHoldInventoryLevel($value)
	{
		$this->ListingHoldInventoryLevel = $value;
	}
/**
 *

 * @return 
 */
	function SellingManagerAutoRelistType()
	{
		$this->EbatNs_ComplexType('SellingManagerAutoRelistType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'Type' =>
				array(
					'required' => false,
					'type' => 'SellingManagerAutoRelistTypeCodeType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'RelistCondition' =>
				array(
					'required' => false,
					'type' => 'SellingManagerAutoRelistOptionCodeType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'RelistAfterDays' =>
				array(
					'required' => false,
					'type' => 'int',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'RelistAfterHours' =>
				array(
					'required' => false,
					'type' => 'int',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'RelistAtSpecificTimeOfDay' =>
				array(
					'required' => false,
					'type' => 'time',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'BestOfferDetails' =>
				array(
					'required' => false,
					'type' => 'BestOfferDetailsType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'ListingHoldInventoryLevel' =>
				array(
					'required' => false,
					'type' => 'int',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				)
			));

	}
}
?>
