<?php
// autogenerated file 29.05.2009 15:17
// $Id: $
// $Log: $
//
//
require_once 'EbatNs_FacetType.php';

class SellingManagerSearchTypeCodeType extends EbatNs_FacetType
{
	// start props
	// @var string $BuyerUserID
	var $BuyerUserID = 'BuyerUserID';
	// @var string $BuyerEmail
	var $BuyerEmail = 'BuyerEmail';
	// @var string $BuyerFullName
	var $BuyerFullName = 'BuyerFullName';
	// @var string $ItemID
	var $ItemID = 'ItemID';
	// @var string $Title
	var $Title = 'Title';
	// @var string $ProductID
	var $ProductID = 'ProductID';
	// @var string $ProductName
	var $ProductName = 'ProductName';
	// @var string $CustomLabel
	var $CustomLabel = 'CustomLabel';
	// @var string $SaleRecordID
	var $SaleRecordID = 'SaleRecordID';
	// @var string $CustomCode
	var $CustomCode = 'CustomCode';
	// end props

/**
 *

 * @return 
 */
	function SellingManagerSearchTypeCodeType()
	{
		$this->EbatNs_FacetType('SellingManagerSearchTypeCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_SellingManagerSearchTypeCodeType = new SellingManagerSearchTypeCodeType();

?>
