<?php
// autogenerated file 29.05.2009 15:17
// $Id: $
// $Log: $
//
//
require_once 'EbatNs_FacetType.php';

class SellingManagerGeneralPropertyTypeCodeType extends EbatNs_FacetType
{
	// start props
	// @var string $NegativeFeedbackReceived
	var $NegativeFeedbackReceived = 'NegativeFeedbackReceived';
	// @var string $UnpaidItemDispute
	var $UnpaidItemDispute = 'UnpaidItemDispute';
	// @var string $BadEmailTemplate
	var $BadEmailTemplate = 'BadEmailTemplate';
	// @var string $CustomCode
	var $CustomCode = 'CustomCode';
	// end props

/**
 *

 * @return 
 */
	function SellingManagerGeneralPropertyTypeCodeType()
	{
		$this->EbatNs_FacetType('SellingManagerGeneralPropertyTypeCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_SellingManagerGeneralPropertyTypeCodeType = new SellingManagerGeneralPropertyTypeCodeType();

?>
