<?php
// autogenerated file 29.05.2009 15:17
// $Id: $
// $Log: $
//
//
require_once 'EbatNs_FacetType.php';

class SellingManagerAlertTypeCodeType extends EbatNs_FacetType
{
	// start props
	// @var string $Sold
	var $Sold = 'Sold';
	// @var string $Inventory
	var $Inventory = 'Inventory';
	// @var string $Automation
	var $Automation = 'Automation';
	// @var string $PaisaPay
	var $PaisaPay = 'PaisaPay';
	// @var string $General
	var $General = 'General';
	// @var string $CustomCode
	var $CustomCode = 'CustomCode';
	// end props

/**
 *

 * @return 
 */
	function SellingManagerAlertTypeCodeType()
	{
		$this->EbatNs_FacetType('SellingManagerAlertTypeCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_SellingManagerAlertTypeCodeType = new SellingManagerAlertTypeCodeType();

?>
