<?php
// autogenerated file 29.05.2009 15:17
// $Id: $
// $Log: $
//
//
require_once 'SellingManagerProductDetailsType.php';
require_once 'EbatNs_ComplexType.php';
require_once 'ItemType.php';

class SellingManagerTemplateDetailsType extends EbatNs_ComplexType
{
	// start props
	// @var string $SaleTemplateID
	var $SaleTemplateID;
	// @var string $SaleTemplateName
	var $SaleTemplateName;
	// @var float $SuccessPercent
	var $SuccessPercent;
	// @var SellingManagerProductDetailsType $SellingManagerProductDetails
	var $SellingManagerProductDetails;
	// @var ItemType $Template
	var $Template;
	// end props

/**
 *

 * @return string
 */
	function getSaleTemplateID()
	{
		return $this->SaleTemplateID;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setSaleTemplateID($value)
	{
		$this->SaleTemplateID = $value;
	}
/**
 *

 * @return string
 */
	function getSaleTemplateName()
	{
		return $this->SaleTemplateName;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setSaleTemplateName($value)
	{
		$this->SaleTemplateName = $value;
	}
/**
 *

 * @return float
 */
	function getSuccessPercent()
	{
		return $this->SuccessPercent;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setSuccessPercent($value)
	{
		$this->SuccessPercent = $value;
	}
/**
 *

 * @return SellingManagerProductDetailsType
 */
	function getSellingManagerProductDetails()
	{
		return $this->SellingManagerProductDetails;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setSellingManagerProductDetails($value)
	{
		$this->SellingManagerProductDetails = $value;
	}
/**
 *

 * @return ItemType
 */
	function getTemplate()
	{
		return $this->Template;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setTemplate($value)
	{
		$this->Template = $value;
	}
/**
 *

 * @return 
 */
	function SellingManagerTemplateDetailsType()
	{
		$this->EbatNs_ComplexType('SellingManagerTemplateDetailsType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'SaleTemplateID' =>
				array(
					'required' => false,
					'type' => 'string',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'SaleTemplateName' =>
				array(
					'required' => false,
					'type' => 'string',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'SuccessPercent' =>
				array(
					'required' => false,
					'type' => 'float',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'SellingManagerProductDetails' =>
				array(
					'required' => false,
					'type' => 'SellingManagerProductDetailsType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'Template' =>
				array(
					'required' => false,
					'type' => 'ItemType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				)
			));

	}
}
?>
