<?php
// autogenerated file 29.05.2009 15:17
// $Id: $
// $Log: $
//
//
require_once 'SellingManagerSoldListingsPropertyTypeCodeType.php';
require_once 'SellingManagerGeneralPropertyTypeCodeType.php';
require_once 'SellingManagerAlertTypeCodeType.php';
require_once 'EbatNs_ComplexType.php';
require_once 'SellingManagerInventoryPropertyTypeCodeType.php';
require_once 'SellingManagerPaisaPayPropertyTypeCodeType.php';
require_once 'SellingManagerAutomationPropertyTypeCodeType.php';

class SellingManagerAlertType extends EbatNs_ComplexType
{
	// start props
	// @var SellingManagerAlertTypeCodeType $AlertType
	var $AlertType;
	// @var SellingManagerSoldListingsPropertyTypeCodeType $SoldAlert
	var $SoldAlert;
	// @var SellingManagerInventoryPropertyTypeCodeType $InventoryAlert
	var $InventoryAlert;
	// @var SellingManagerAutomationPropertyTypeCodeType $AutomationAlert
	var $AutomationAlert;
	// @var SellingManagerPaisaPayPropertyTypeCodeType $PaisaPayAlert
	var $PaisaPayAlert;
	// @var SellingManagerGeneralPropertyTypeCodeType $GeneralAlert
	var $GeneralAlert;
	// @var int $DurationInDays
	var $DurationInDays;
	// @var long $Count
	var $Count;
	// end props

/**
 *

 * @return SellingManagerAlertTypeCodeType
 */
	function getAlertType()
	{
		return $this->AlertType;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setAlertType($value)
	{
		$this->AlertType = $value;
	}
/**
 *

 * @return SellingManagerSoldListingsPropertyTypeCodeType
 */
	function getSoldAlert()
	{
		return $this->SoldAlert;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setSoldAlert($value)
	{
		$this->SoldAlert = $value;
	}
/**
 *

 * @return SellingManagerInventoryPropertyTypeCodeType
 */
	function getInventoryAlert()
	{
		return $this->InventoryAlert;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setInventoryAlert($value)
	{
		$this->InventoryAlert = $value;
	}
/**
 *

 * @return SellingManagerAutomationPropertyTypeCodeType
 */
	function getAutomationAlert()
	{
		return $this->AutomationAlert;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setAutomationAlert($value)
	{
		$this->AutomationAlert = $value;
	}
/**
 *

 * @return SellingManagerPaisaPayPropertyTypeCodeType
 */
	function getPaisaPayAlert()
	{
		return $this->PaisaPayAlert;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setPaisaPayAlert($value)
	{
		$this->PaisaPayAlert = $value;
	}
/**
 *

 * @return SellingManagerGeneralPropertyTypeCodeType
 */
	function getGeneralAlert()
	{
		return $this->GeneralAlert;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setGeneralAlert($value)
	{
		$this->GeneralAlert = $value;
	}
/**
 *

 * @return int
 */
	function getDurationInDays()
	{
		return $this->DurationInDays;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setDurationInDays($value)
	{
		$this->DurationInDays = $value;
	}
/**
 *

 * @return long
 */
	function getCount()
	{
		return $this->Count;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setCount($value)
	{
		$this->Count = $value;
	}
/**
 *

 * @return 
 */
	function SellingManagerAlertType()
	{
		$this->EbatNs_ComplexType('SellingManagerAlertType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'AlertType' =>
				array(
					'required' => false,
					'type' => 'SellingManagerAlertTypeCodeType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'SoldAlert' =>
				array(
					'required' => false,
					'type' => 'SellingManagerSoldListingsPropertyTypeCodeType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'InventoryAlert' =>
				array(
					'required' => false,
					'type' => 'SellingManagerInventoryPropertyTypeCodeType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'AutomationAlert' =>
				array(
					'required' => false,
					'type' => 'SellingManagerAutomationPropertyTypeCodeType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'PaisaPayAlert' =>
				array(
					'required' => false,
					'type' => 'SellingManagerPaisaPayPropertyTypeCodeType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'GeneralAlert' =>
				array(
					'required' => false,
					'type' => 'SellingManagerGeneralPropertyTypeCodeType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'DurationInDays' =>
				array(
					'required' => false,
					'type' => 'int',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'Count' =>
				array(
					'required' => false,
					'type' => 'long',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				)
			));

	}
}
?>
