<?php
// autogenerated file 29.05.2009 15:17
// $Id: $
// $Log: $
//
//
require_once 'AbstractResponseType.php';

class SendInvoiceResponseType extends AbstractResponseType
{
	// start props
	// end props

/**
 *

 * @return 
 */
	function SendInvoiceResponseType()
	{
		$this->AbstractResponseType('SendInvoiceResponseType', 'urn:ebay:apis:eBLBaseComponents');

	}
}
?>
