<?php
// autogenerated file 29.05.2009 15:17
// $Id: $
// $Log: $
//
//
require_once 'AutomatedLeaveFeedbackEventCodeType.php';
require_once 'FeedbackCommentArrayType.php';
require_once 'AbstractRequestType.php';

class SetSellingManagerFeedbackOptionsRequestType extends AbstractRequestType
{
	// start props
	// @var AutomatedLeaveFeedbackEventCodeType $AutomatedLeaveFeedbackEvent
	var $AutomatedLeaveFeedbackEvent;
	// @var FeedbackCommentArrayType $StoredComments
	var $StoredComments;
	// end props

/**
 *

 * @return AutomatedLeaveFeedbackEventCodeType
 */
	function getAutomatedLeaveFeedbackEvent()
	{
		return $this->AutomatedLeaveFeedbackEvent;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setAutomatedLeaveFeedbackEvent($value)
	{
		$this->AutomatedLeaveFeedbackEvent = $value;
	}
/**
 *

 * @return FeedbackCommentArrayType
 */
	function getStoredComments()
	{
		return $this->StoredComments;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setStoredComments($value)
	{
		$this->StoredComments = $value;
	}
/**
 *

 * @return 
 */
	function SetSellingManagerFeedbackOptionsRequestType()
	{
		$this->AbstractRequestType('SetSellingManagerFeedbackOptionsRequestType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'AutomatedLeaveFeedbackEvent' =>
				array(
					'required' => false,
					'type' => 'AutomatedLeaveFeedbackEventCodeType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'StoredComments' =>
				array(
					'required' => false,
					'type' => 'FeedbackCommentArrayType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				)
			));

	}
}
?>
