<?php
// autogenerated file 29.05.2009 15:17
// $Id: $
// $Log: $
//
//
require_once 'SellingManagerAutoRelistType.php';
require_once 'SellingManagerAutoListType.php';
require_once 'SellingManagerAutoSecondChanceOfferType.php';
require_once 'AbstractRequestType.php';

class SetSellingManagerTemplateAutomationRuleRequestType extends AbstractRequestType
{
	// start props
	// @var long $SaleTemplateID
	var $SaleTemplateID;
	// @var SellingManagerAutoListType $AutomatedListingRule
	var $AutomatedListingRule;
	// @var SellingManagerAutoRelistType $AutomatedRelistingRule
	var $AutomatedRelistingRule;
	// @var SellingManagerAutoSecondChanceOfferType $AutomatedSecondChanceOfferRule
	var $AutomatedSecondChanceOfferRule;
	// end props

/**
 *

 * @return long
 */
	function getSaleTemplateID()
	{
		return $this->SaleTemplateID;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setSaleTemplateID($value)
	{
		$this->SaleTemplateID = $value;
	}
/**
 *

 * @return SellingManagerAutoListType
 */
	function getAutomatedListingRule()
	{
		return $this->AutomatedListingRule;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setAutomatedListingRule($value)
	{
		$this->AutomatedListingRule = $value;
	}
/**
 *

 * @return SellingManagerAutoRelistType
 */
	function getAutomatedRelistingRule()
	{
		return $this->AutomatedRelistingRule;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setAutomatedRelistingRule($value)
	{
		$this->AutomatedRelistingRule = $value;
	}
/**
 *

 * @return SellingManagerAutoSecondChanceOfferType
 */
	function getAutomatedSecondChanceOfferRule()
	{
		return $this->AutomatedSecondChanceOfferRule;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setAutomatedSecondChanceOfferRule($value)
	{
		$this->AutomatedSecondChanceOfferRule = $value;
	}
/**
 *

 * @return 
 */
	function SetSellingManagerTemplateAutomationRuleRequestType()
	{
		$this->AbstractRequestType('SetSellingManagerTemplateAutomationRuleRequestType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'SaleTemplateID' =>
				array(
					'required' => false,
					'type' => 'long',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'AutomatedListingRule' =>
				array(
					'required' => false,
					'type' => 'SellingManagerAutoListType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'AutomatedRelistingRule' =>
				array(
					'required' => false,
					'type' => 'SellingManagerAutoRelistType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'AutomatedSecondChanceOfferRule' =>
				array(
					'required' => false,
					'type' => 'SellingManagerAutoSecondChanceOfferType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				)
			));

	}
}
?>
