<?php
// autogenerated file 29.05.2009 15:17
// $Id: $
// $Log: $
//
//
require_once 'EbatNs_FacetType.php';

class SetUserNotesActionCodeType extends EbatNs_FacetType
{
	// start props
	// @var string $AddOrUpdate
	var $AddOrUpdate = 'AddOrUpdate';
	// @var string $Delete
	var $Delete = 'Delete';
	// @var string $CustomCode
	var $CustomCode = 'CustomCode';
	// end props

/**
 *

 * @return 
 */
	function SetUserNotesActionCodeType()
	{
		$this->EbatNs_FacetType('SetUserNotesActionCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_SetUserNotesActionCodeType = new SetUserNotesActionCodeType();

?>
