<?php
// autogenerated file 29.05.2009 15:17
// $Id: $
// $Log: $
//
//
require_once 'ShippingPackageCodeType.php';
require_once 'EbatNs_ComplexType.php';

class ShippingServicePackageDetailsType extends EbatNs_ComplexType
{
	// start props
	// @var ShippingPackageCodeType $Name
	var $Name;
	// @var boolean $DimensionsRequired
	var $DimensionsRequired;
	// end props

/**
 *

 * @return ShippingPackageCodeType
 */
	function getName()
	{
		return $this->Name;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setName($value)
	{
		$this->Name = $value;
	}
/**
 *

 * @return boolean
 */
	function getDimensionsRequired()
	{
		return $this->DimensionsRequired;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setDimensionsRequired($value)
	{
		$this->DimensionsRequired = $value;
	}
/**
 *

 * @return 
 */
	function ShippingServicePackageDetailsType()
	{
		$this->EbatNs_ComplexType('ShippingServicePackageDetailsType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'Name' =>
				array(
					'required' => false,
					'type' => 'ShippingPackageCodeType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'DimensionsRequired' =>
				array(
					'required' => false,
					'type' => 'boolean',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				)
			));

	}
}
?>
