<?php
// autogenerated file 29.05.2009 15:17
// $Id: $
// $Log: $
//
//
require_once 'EbatNs_ComplexType.php';

class ShippingCostPaidByDetailsType extends EbatNs_ComplexType
{
	// start props
	// @var token $ShippingCostPaidByOption
	var $ShippingCostPaidByOption;
	// @var string $Description
	var $Description;
	// end props

/**
 *

 * @return token
 */
	function getShippingCostPaidByOption()
	{
		return $this->ShippingCostPaidByOption;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setShippingCostPaidByOption($value)
	{
		$this->ShippingCostPaidByOption = $value;
	}
/**
 *

 * @return string
 */
	function getDescription()
	{
		return $this->Description;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setDescription($value)
	{
		$this->Description = $value;
	}
/**
 *

 * @return 
 */
	function ShippingCostPaidByDetailsType()
	{
		$this->EbatNs_ComplexType('ShippingCostPaidByDetailsType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'ShippingCostPaidByOption' =>
				array(
					'required' => false,
					'type' => 'token',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'Description' =>
				array(
					'required' => false,
					'type' => 'string',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				)
			));

	}
}
?>
