<?php
// autogenerated file 29.05.2009 15:17
// $Id: $
// $Log: $
//
//
require_once 'EbatNs_FacetType.php';

class ShippingCostPaidByOptionsCodeType extends EbatNs_FacetType
{
	// start props
	// @var string $Buyer
	var $Buyer = 'Buyer';
	// @var string $Seller
	var $Seller = 'Seller';
	// @var string $CustomCode
	var $CustomCode = 'CustomCode';
	// end props

/**
 *

 * @return 
 */
	function ShippingCostPaidByOptionsCodeType()
	{
		$this->EbatNs_FacetType('ShippingCostPaidByOptionsCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_ShippingCostPaidByOptionsCodeType = new ShippingCostPaidByOptionsCodeType();

?>
