<?php
// autogenerated file 29.05.2009 15:17
// $Id: $
// $Log: $
//
//
require_once 'EbatNs_SimpleType.php';

class SKUType extends EbatNs_SimpleType
{
	// start props
	// end props

/**
 *

 * @return 
 */
	function SKUType()
	{
		$this->EbatNs_SimpleType('SKUType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_SKUType = new SKUType();

?>
