<?php
// autogenerated file 29.05.2009 15:17
// $Id: $
// $Log: $
//
//
require_once 'EbatNs_FacetType.php';

class StoreCustomListingHeaderDisplayCodeType extends EbatNs_FacetType
{
	// start props
	// @var string $None
	var $None = 'None';
	// @var string $Full
	var $Full = 'Full';
	// @var string $FullAndLeftNavigationBar
	var $FullAndLeftNavigationBar = 'FullAndLeftNavigationBar';
	// @var string $CustomCode
	var $CustomCode = 'CustomCode';
	// end props

/**
 *

 * @return 
 */
	function StoreCustomListingHeaderDisplayCodeType()
	{
		$this->EbatNs_FacetType('StoreCustomListingHeaderDisplayCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_StoreCustomListingHeaderDisplayCodeType = new StoreCustomListingHeaderDisplayCodeType();

?>
