<?php
// autogenerated file 29.05.2009 15:17
// $Id: $
// $Log: $
//
//
require_once 'EbatNs_ComplexType.php';
require_once 'TokenStatusCodeType.php';

class TokenStatusType extends EbatNs_ComplexType
{
	// start props
	// @var TokenStatusCodeType $Status
	var $Status;
	// @var string $EIASToken
	var $EIASToken;
	// @var dateTime $ExpirationTime
	var $ExpirationTime;
	// @var dateTime $RevocationTime
	var $RevocationTime;
	// end props

/**
 *

 * @return TokenStatusCodeType
 */
	function getStatus()
	{
		return $this->Status;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setStatus($value)
	{
		$this->Status = $value;
	}
/**
 *

 * @return string
 */
	function getEIASToken()
	{
		return $this->EIASToken;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setEIASToken($value)
	{
		$this->EIASToken = $value;
	}
/**
 *

 * @return dateTime
 */
	function getExpirationTime()
	{
		return $this->ExpirationTime;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setExpirationTime($value)
	{
		$this->ExpirationTime = $value;
	}
/**
 *

 * @return dateTime
 */
	function getRevocationTime()
	{
		return $this->RevocationTime;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setRevocationTime($value)
	{
		$this->RevocationTime = $value;
	}
/**
 *

 * @return 
 */
	function TokenStatusType()
	{
		$this->EbatNs_ComplexType('TokenStatusType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'Status' =>
				array(
					'required' => false,
					'type' => 'TokenStatusCodeType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				),
				'EIASToken' =>
				array(
					'required' => false,
					'type' => 'string',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'ExpirationTime' =>
				array(
					'required' => false,
					'type' => 'dateTime',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'RevocationTime' =>
				array(
					'required' => false,
					'type' => 'dateTime',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				)
			));

	}
}
?>
