<?php
// autogenerated file 29.05.2009 15:17
// $Id: $
// $Log: $
//
//
require_once 'EbatNs_FacetType.php';

class TokenStatusCodeType extends EbatNs_FacetType
{
	// start props
	// @var string $Active
	var $Active = 'Active';
	// @var string $Expired
	var $Expired = 'Expired';
	// @var string $RevokedByeBay
	var $RevokedByeBay = 'RevokedByeBay';
	// @var string $RevokedByUser
	var $RevokedByUser = 'RevokedByUser';
	// @var string $RevokedByApp
	var $RevokedByApp = 'RevokedByApp';
	// @var string $Invalid
	var $Invalid = 'Invalid';
	// @var string $CustomCode
	var $CustomCode = 'CustomCode';
	// end props

/**
 *

 * @return 
 */
	function TokenStatusCodeType()
	{
		$this->EbatNs_FacetType('TokenStatusCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_TokenStatusCodeType = new TokenStatusCodeType();

?>
