<?php
// autogenerated file 29.05.2009 15:17
// $Id: $
// $Log: $
//
//
require_once 'EbatNs_FacetType.php';

class UnitCodeType extends EbatNs_FacetType
{
	// start props
	// @var string $kg
	var $kg = 'kg';
	// @var string $gm
	var $gm = 'gm';
	// @var string $lbs
	var $lbs = 'lbs';
	// @var string $oz
	var $oz = 'oz';
	// @var string $cm
	var $cm = 'cm';
	// @var string $mm
	var $mm = 'mm';
	// @var string $inches
	var $inches = 'inches';
	// @var string $ft
	var $ft = 'ft';
	// @var string $CustomCode
	var $CustomCode = 'CustomCode';
	// end props

/**
 *

 * @return 
 */
	function UnitCodeType()
	{
		$this->EbatNs_FacetType('UnitCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_UnitCodeType = new UnitCodeType();

?>
