<?php
// autogenerated file 29.05.2009 15:17
// $Id: $
// $Log: $
//
//
require_once 'UserIDType.php';
require_once 'EbatNs_ComplexType.php';

class UserIDArrayType extends EbatNs_ComplexType
{
	// start props
	// @var UserIDType $UserID
	var $UserID;
	// end props

/**
 *

 * @return UserIDType
 * @param  $index 
 */
	function getUserID($index = null)
	{
		if ($index) {
		return $this->UserID[$index];
	} else {
		return $this->UserID;
	}

	}
/**
 *

 * @return void
 * @param  $value 
 * @param  $index 
 */
	function setUserID($value, $index = null)
	{
		if ($index) {
	$this->UserID[$index] = $value;
	} else {
	$this->UserID = $value;
	}

	}
/**
 *

 * @return 
 */
	function UserIDArrayType()
	{
		$this->EbatNs_ComplexType('UserIDArrayType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'UserID' =>
				array(
					'required' => false,
					'type' => 'UserIDType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => true,
					'cardinality' => '0..*'
				)
			));

	}
}
?>
