<?php
// autogenerated file 29.05.2009 15:17
// $Id: $
// $Log: $
//
//
require_once 'EbatNs_FacetType.php';

class ValueTypeCodeType extends EbatNs_FacetType
{
	// start props
	// @var string $Decimal
	var $Decimal = 'Decimal';
	// @var string $Text
	var $Text = 'Text';
	// @var string $ISBN
	var $ISBN = 'ISBN';
	// @var string $UPC
	var $UPC = 'UPC';
	// @var string $EAN
	var $EAN = 'EAN';
	// @var string $CustomCode
	var $CustomCode = 'CustomCode';
	// end props

/**
 *

 * @return 
 */
	function ValueTypeCodeType()
	{
		$this->EbatNs_FacetType('ValueTypeCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_ValueTypeCodeType = new ValueTypeCodeType();

?>
