<?php
// autogenerated file 29.05.2009 15:17
// $Id: $
// $Log: $
//
//
require_once 'EbatNs_FacetType.php';

class VariationPictureRuleCodeType extends EbatNs_FacetType
{
	// start props
	// @var string $Required
	var $Required = 'Required';
	// @var string $Enabled
	var $Enabled = 'Enabled';
	// @var string $Disabled
	var $Disabled = 'Disabled';
	// @var string $CustomCode
	var $CustomCode = 'CustomCode';
	// end props

/**
 *

 * @return 
 */
	function VariationPictureRuleCodeType()
	{
		$this->EbatNs_FacetType('VariationPictureRuleCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_VariationPictureRuleCodeType = new VariationPictureRuleCodeType();

?>
