<?php
// autogenerated file 29.05.2009 15:17
// $Id: $
// $Log: $
//
//
require_once 'EbatNs_ComplexType.php';

class VariationSpecificPictureSetType extends EbatNs_ComplexType
{
	// start props
	// @var string $VariationSpecificValue
	var $VariationSpecificValue;
	// @var anyURI $PictureURL
	var $PictureURL;
	// @var anyURI $GalleryURL
	var $GalleryURL;
	// end props

/**
 *

 * @return string
 */
	function getVariationSpecificValue()
	{
		return $this->VariationSpecificValue;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setVariationSpecificValue($value)
	{
		$this->VariationSpecificValue = $value;
	}
/**
 *

 * @return anyURI
 * @param  $index 
 */
	function getPictureURL($index = null)
	{
		if ($index) {
		return $this->PictureURL[$index];
	} else {
		return $this->PictureURL;
	}

	}
/**
 *

 * @return void
 * @param  $value 
 * @param  $index 
 */
	function setPictureURL($value, $index = null)
	{
		if ($index) {
	$this->PictureURL[$index] = $value;
	} else {
	$this->PictureURL = $value;
	}

	}
/**
 *

 * @return anyURI
 */
	function getGalleryURL()
	{
		return $this->GalleryURL;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setGalleryURL($value)
	{
		$this->GalleryURL = $value;
	}
/**
 *

 * @return 
 */
	function VariationSpecificPictureSetType()
	{
		$this->EbatNs_ComplexType('VariationSpecificPictureSetType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'VariationSpecificValue' =>
				array(
					'required' => false,
					'type' => 'string',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				),
				'PictureURL' =>
				array(
					'required' => false,
					'type' => 'anyURI',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => true,
					'cardinality' => '0..*'
				),
				'GalleryURL' =>
				array(
					'required' => false,
					'type' => 'anyURI',
					'nsURI' => 'http://www.w3.org/2001/XMLSchema',
					'array' => false,
					'cardinality' => '0..1'
				)
			));

	}
}
?>
