<?php
// autogenerated file 29.05.2009 15:17
// $Id: $
// $Log: $
//
//
require_once 'VariationType.php';
require_once 'EbatNs_ComplexType.php';
require_once 'PicturesType.php';
require_once 'NameValueListArrayType.php';

class VariationsType extends EbatNs_ComplexType
{
	// start props
	// @var VariationType $Variation
	var $Variation;
	// @var PicturesType $Pictures
	var $Pictures;
	// @var NameValueListArrayType $VariationSpecificsSet
	var $VariationSpecificsSet;
	// end props

/**
 *

 * @return VariationType
 * @param  $index 
 */
	function getVariation($index = null)
	{
		if ($index) {
		return $this->Variation[$index];
	} else {
		return $this->Variation;
	}

	}
/**
 *

 * @return void
 * @param  $value 
 * @param  $index 
 */
	function setVariation($value, $index = null)
	{
		if ($index) {
	$this->Variation[$index] = $value;
	} else {
	$this->Variation = $value;
	}

	}
/**
 *

 * @return PicturesType
 * @param  $index 
 */
	function getPictures($index = null)
	{
		if ($index) {
		return $this->Pictures[$index];
	} else {
		return $this->Pictures;
	}

	}
/**
 *

 * @return void
 * @param  $value 
 * @param  $index 
 */
	function setPictures($value, $index = null)
	{
		if ($index) {
	$this->Pictures[$index] = $value;
	} else {
	$this->Pictures = $value;
	}

	}
/**
 *

 * @return NameValueListArrayType
 */
	function getVariationSpecificsSet()
	{
		return $this->VariationSpecificsSet;
	}
/**
 *

 * @return void
 * @param  $value 
 */
	function setVariationSpecificsSet($value)
	{
		$this->VariationSpecificsSet = $value;
	}
/**
 *

 * @return 
 */
	function VariationsType()
	{
		$this->EbatNs_ComplexType('VariationsType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'Variation' =>
				array(
					'required' => false,
					'type' => 'VariationType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => true,
					'cardinality' => '0..*'
				),
				'Pictures' =>
				array(
					'required' => false,
					'type' => 'PicturesType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => true,
					'cardinality' => '0..*'
				),
				'VariationSpecificsSet' =>
				array(
					'required' => false,
					'type' => 'NameValueListArrayType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => false,
					'cardinality' => '0..1'
				)
			));

	}
}
?>
