<?php
// autogenerated file 29.05.2009 15:17
// $Id: $
// $Log: $
//
//
require_once 'VeROSiteDetailType.php';
require_once 'EbatNs_ComplexType.php';

class VeROReasonCodeDetailsType extends EbatNs_ComplexType
{
	// start props
	// @var VeROSiteDetailType $VeROSiteDetail
	var $VeROSiteDetail;
	// end props

/**
 *

 * @return VeROSiteDetailType
 * @param  $index 
 */
	function getVeROSiteDetail($index = null)
	{
		if ($index) {
		return $this->VeROSiteDetail[$index];
	} else {
		return $this->VeROSiteDetail;
	}

	}
/**
 *

 * @return void
 * @param  $value 
 * @param  $index 
 */
	function setVeROSiteDetail($value, $index = null)
	{
		if ($index) {
	$this->VeROSiteDetail[$index] = $value;
	} else {
	$this->VeROSiteDetail = $value;
	}

	}
/**
 *

 * @return 
 */
	function VeROReasonCodeDetailsType()
	{
		$this->EbatNs_ComplexType('VeROReasonCodeDetailsType', 'urn:ebay:apis:eBLBaseComponents');
		$this->_elements = array_merge($this->_elements,
			array(
				'VeROSiteDetail' =>
				array(
					'required' => false,
					'type' => 'VeROSiteDetailType',
					'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
					'array' => true,
					'cardinality' => '0..*'
				)
			));

	}
}
?>
