<?php
// autogenerated file 29.05.2009 15:17
// $Id: $
// $Log: $
//
//
require_once 'EbatNs_FacetType.php';

class WarrantyTypeOptionsCodeType extends EbatNs_FacetType
{
	// start props
	// @var string $ReplacementWarranty
	var $ReplacementWarranty = 'ReplacementWarranty';
	// @var string $DealerWarranty
	var $DealerWarranty = 'DealerWarranty';
	// @var string $ManufacturerWarranty
	var $ManufacturerWarranty = 'ManufacturerWarranty';
	// @var string $CustomCode
	var $CustomCode = 'CustomCode';
	// end props

/**
 *

 * @return 
 */
	function WarrantyTypeOptionsCodeType()
	{
		$this->EbatNs_FacetType('WarrantyTypeOptionsCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_WarrantyTypeOptionsCodeType = new WarrantyTypeOptionsCodeType();

?>
