<?php
// autogenerated file 29.05.2009 15:17
// $Id: $
// $Log: $
//
//
require_once 'EbatNs_FacetType.php';

class WarrantyDurationOptionsCodeType extends EbatNs_FacetType
{
	// start props
	// @var string $Months_1
	var $Months_1 = 'Months_1';
	// @var string $Months_3
	var $Months_3 = 'Months_3';
	// @var string $Months_6
	var $Months_6 = 'Months_6';
	// @var string $Years_1
	var $Years_1 = 'Years_1';
	// @var string $Years_2
	var $Years_2 = 'Years_2';
	// @var string $Years_3
	var $Years_3 = 'Years_3';
	// @var string $Years_MoreThan3
	var $Years_MoreThan3 = 'Years_MoreThan3';
	// @var string $CustomCode
	var $CustomCode = 'CustomCode';
	// end props

/**
 *

 * @return 
 */
	function WarrantyDurationOptionsCodeType()
	{
		$this->EbatNs_FacetType('WarrantyDurationOptionsCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_WarrantyDurationOptionsCodeType = new WarrantyDurationOptionsCodeType();

?>
