#!/bin/bash
chmod 0644 includes/configure.php
chmod 0644 admin/includes/configure.php
chmod 0777 images/
chmod 0777 admin/backups/
chmod 0777 admin/xml/
chmod 0777 temp
chmod -R 0777 download/
chmod -R 0777 affiliates/
chmod -R 0777 includes/languages
chmod -R 0777 admin/images/graphs
chmod -R 0777 templates/Original/images
chmod 0777 templates
chmod 0666 for_upload.txt
chmod 0777 for_upload
for a in `find ./ -name "*.php" -print`
 do 
    chmod a-x $a
done 
for a in `find ./admin/images/graphs/ -name "*.png" -print`
do
  chmod 0666 $a
done
for a in `find ./images/ -type f -print`
 do
    chmod 0666 $a
done
chmod 0644 ./images/.htaccess

